<?php $storeId = Mage::app()->getStore()->getStoreId(); ?>
  <div class="registration-container">
    <div class="switch-wrapper">
      <ul class="switch">
        <li id="switch-signup" class="active"><?php echo $this->__('Become a Member') ?></li>
        <li id="switch-login"><?php echo $this->__('Login') ?></li>
      </ul>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <div class="content-wrapper">
      <div id="signup">
        <form id="registration-form" action="<?php echo $this->getActionUrl('registration'); ?>" method="post">
          <input type="hidden" name="success_url" value="<?php echo $this->getUrl('aktionen') ?>" />
          <!-- <input type="hidden" name="error_url" value="<?php //echo $this->getErrorUrl() ?>" /> -->
          <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
          <input type="hidden" name="is_subscribed" value="1" checked="checked" />
          <div id="reg-step-one">
            <h1><?php echo $this->__('Become a Member for free now.') ?></h1>
            <div class="usp-wrapper">
              <ul class="list-style-checkmark">
                <li>
                  <?php echo $this->__('Save up to 70% on Fashion and Equipment') ?>
                </li>
                <li>
                  <?php echo $this->__('New campaigns daily') ?>
                </li>
                <li>
                  <?php echo $this->__('Find exclusive Brands and Products') ?>
                </li>
              </ul>
            </div>

            <input type="text" name="email" id="reg-email" placeholder="<?php echo $this->__('Your E-Mail Address') ?>" />
            <p class="note registration-terms">
              Mit der Anmeldung stimme ich den <a>AGB</a> und <a>Datenschutzbestimmungen</a> zu und erhalte regelm&auml;&szlig;ig einen Newsletter, den ich jederzeit kostenfrei abbestellen kann.
            </p>
            <button type="button" class="gold expand reg-continue"><?php echo $this->__('Sign In for free'); ?></button>
            <?php
            $block = $this->getLayout()->createBlock('inchoo_socialconnect/facebook_button')->setButtonText('Login mit Facebook');
            echo $block->setTemplate('inchoo/socialconnect/facebook/button.phtml')->toHtml();
            ?>
            <?php /* <button class="btn black expand"><?php echo $this->__('Sign In with Facebook'); ?></button> */ ?>
          </div>
          <div id="reg-step-two" class="hide">
            <input class="required-entry input-text" type="text" name="firstname" placeholder="<?php echo $this->__('Your Firstname') ?>" />
            <input class="required-entry input-text" type="text" name="lastname" placeholder="<?php echo $this->__('Your Lastname') ?>" />
            <input class="required-entry input-text" type="password" name="password" placeholder="<?php echo $this->__('Your Password') ?>" />
            <input class="required-entry input-text" type="password" name="confirmation" placeholder="<?php echo $this->__('Confirm Your Password') ?>" />
            <button class="gold expand" type="button" onclick="signupForm.submit();" style="margin-top: 1rem;"><?php echo $this->__('Sign In'); ?></button>
          </div>
          <div class="content-bottom" style="display: none;">
          </div>
        </form>
      </div>
      <div id="login" class="hide">
        <form id="login-form" action="<?php echo $this->getActionUrl('login'); ?>" method="post">
          <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
          <input type="hidden" name="aktionenlogin" value='true' />
          <h1>Anmelden</h1>
          <input class="required-entry input-text" type="text" name="login[username]" placeholder="<?php echo $this->__('Your E-Mail Address') ?>" />
          <input id="login-password" class="required-entry input-text" type="password" name="login[password]" placeholder="<?php echo $this->__('Your Password') ?>"/>
          <div class="persistend-forgot-wrapper">
            <div class="persistent-login">
              <label>
                <?php echo $this->__("Stay logged in") ?>
                <input type="checkbox" name="persistend.login" checked="checked" />
              </label>
            </div>
            <div class="forgot-password">
              <a id="forgotpassword-link" href="#newPassword"><?php echo $this->__("Forgot Password") ?>?</a>
            </div>
          </div>
          <button class="gold expand" type="button" onclick="loginForm.submit();"><?php echo $this->__('Log In'); ?></button>
          <?php
          $block = $this->getLayout()->createBlock('inchoo_socialconnect/facebook_button')->setButtonText('Login mit Facebook');
          echo $block->setTemplate('inchoo/socialconnect/facebook/button.phtml')->toHtml();
          ?>
        </form>
      </div>
      <div id="forgotpassword" class="hide">
        <form action="<?php echo $this->getUrl('customer/account/forgotpasswordpost') ?>" method="post" id="forgottpassword-form">
          <p class="form-instructions"><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
          <input class="required-entry input-text" type="text" name="email" placeholder="<?php echo $this->__('Your E-Mail Address') ?>" />
          <button type="button" class="gold expand" onclick="forgottpasswordForm.submit();" style="margin-top: 1em;">Passwort anfordern</button>
          <a id="forgotpassword-back-link"><?php echo '< '.$this->__('Back') ?></a>
        </form>
      </div>
    </div>
  </div>
<script type="text/javascript">
//<![CDATA[

  jQuery('#login-password').keyup(function(e) {
    if(e.keyCode == 13) {
      jQuery('#login-form').submit();
    }
  });

  var $j = jQuery;
  $j("ul.switch li").click(function(ev) {
    if($j(this).is('#switch-signup') && !$j(this).hasClass('active')) {
      $j('#signup').removeClass('hide');
      $j('#login').addClass('hide');
      $j('#forgotpassword').addClass('hide');
      $j('#switch-signup').addClass('active');
      $j('#switch-login').removeClass('active');
    }
    if($j(this).is('#switch-login') && !$j(this).hasClass('active')) {
      $j('#login').removeClass('hide');
      $j('#signup').addClass('hide');
      $j('#forgotpassword').addClass('hide');
      $j('#switch-signup').removeClass('active');
      $j('#switch-login').addClass('active');
    }
  });

  $j('#forgotpassword-link').click(function(e) {
    e.preventDefault();
    $j('#login').addClass('hide');
    $j('#signup').addClass('hide');
    $j('#forgotpassword').removeClass('hide');
  });

  $j('#forgotpassword-back-link').click(function(e) {
    e.preventDefault();
    $j('#login').removeClass('hide');
    $j('#signup').addClass('hide');
    $j('#forgotpassword').addClass('hide');
  });

  $j("#registration-form button.reg-continue").on('click', function(ev) {
    // mehr validation
    if($j('#reg-email').val().length > 0) {
      $j('#reg-step-one').addClass('hide');
      $j('#reg-step-two').removeClass('hide');
    }
  });

  var loginForm = new VarienForm('login-form', true);
  var signupForm = new VarienForm('registration-form', true);
  var forgottpasswordForm = new VarienForm('forgottpassword-form', true);

//]]>
</script>
