<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);

$manufacturer = null;
$deliveryInfo = null;

if($_item->getProduct()->getData('manufacturer')) { $manufacturer = $_item->getProduct()->getAttributeText('manufacturer'); }
if($_item->getProduct()->getData('delivery_time')) { $deliveryInfo = $_item->getProduct()->getAttributeText('delivery_time'); }

?>

<tr>
  <td class="product-image">
    <img src="<?php echo $this->getProductThumbnail()->resize(180); ?>" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>"
        class="img-responsive"/>
  </td>
  <td class="text-left product-details">
    <?php if($manufacturer && $manufacturer != ''): ?><span><strong><?php echo $manufacturer ?></strong></span><?php endif; ?>
    <span><?php echo $this->escapeHtml($this->getProductName()) ?></span>
    <span>Artikelnummer: <?php echo $this->escapeHtml($_item->getSku()); ?></span>
    <?php if($deliveryInfo && $deliveryInfo != ''): ?><span><?php echo $deliveryInfo ?></span><?php endif; ?>
    <a href="<?php echo $this->getDeleteUrl() ?>" class="btn shopping-cart remove"><i class="fa fa-times-circle-o"></i> Artikel entfernen</a>
  </td>

  <td class="product-attributes">
    <?php if ($_options = $this->getOptionList()):?>
    <div class="item-options">
      <?php foreach ($_options as $_option) : ?>
      <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
        <span><?php echo $this->escapeHtml($_option['label']) ?>: <?php echo $_formatedOptionValue['value'] ?></span>
      <?php endforeach; ?>
    </div>
    <?php endif;?>
  </td>

  <?php // Hier soll ein Dropdown hin! ?>
  <td class="product-qty">
    <input type="text" pattern="\d*" name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="4"
           data-cart-item-id="<?php echo $this->jsQuoteEscape($_item->getSku()) ?>"
           title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty" maxlength="12" />

    <button type="submit" name="update_cart_action" data-cart-item-update value="update_qty" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Update')); ?>" class="button btn-update">
      <i class="fa fa-refresh" style="margin-left: 0;"></i>
    </button>
  </td>

  <td class="product-price">
    <strong>
      <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <?php echo $this->helper('checkout')->formatPrice( $this->helper('checkout')->getPriceInclTax($_item) ); ?>
      <?php elseif($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <?php echo $this->helper('checkout')->formatPrice( $_item->getCalculationPrice() ); ?>
      <?php endif; ?>
    </strong>
  </td>

</tr>
