<?php
  $_helper = $this->helper('catalog/output');
  $products = $this->getProductCollection();
?>
<?php if(count($products)): ?>
<div class="box-collateral">
  <div id="bestselling-products">
    <?php foreach ($products as $_product): ?>
      <?php $manufacturer = $_product->getAttributeText('manufacturer'); ?>

      <div class="bestseller-product productlist-element">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
          <img id="product-collection-image-<?php echo $_product->getId(); ?>"
            src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(232,245); ?>" width="232" height="245"
            alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
        </a>
        <div class="product-info">
          <div class="top-row">
            <div class="product-manufacturer"><?php echo ($manufacturer != '' ? $manufacturer : '&nbsp;'); ?></div>
            <div class="product-price"><?php echo Mage::helper('core')->currency($_product->getFinalPrice(),true,false); ?></div>
            <?php /* $_msrp = $_helper->productAttribute($_product, $_product->getMsrp(), 'msrp') ?>
            <?php $_msrpPrice = $this->helper('core')->currency($_msrp,true,true) ?>
            <?php if($_msrp): ?>
              <span class="msrp"><?php echo $_msrpPrice; ?></span>
            <?php endif; */ ?>
          </div>
          <div class="bottom-row">
            <span class="product-name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>
          </div>
        </div>
          <?php
          // Provides extra blocks on which to hang some features for products in the list
          // Features providing UI elements targeting this block will display directly below the product name
          if ($this->getChild('name.after')) {
              $_nameAfterChildName = 'product_list.swatches';
              if ($_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName)) {
                echo '<div class="offcanvas offcanvas-left">';
                $_nameAfterChild->setProduct($_product);
                echo $_nameAfterChild->toHtml();
                echo '</div>';
              }
          }
          ?>
          <?php /*
          <div class="offcanvas offcanvas-bottom">
            foundation badges <?php echo 'saleable: ' . ($_product->isSaleable() ? 'true' : 'false') ?>
            <?php
            // Provides extra blocks on which to hang some features for products in the list
            // Features providing UI elements targeting this block will display directly below the product name
            if (false && $this->getChild('name.after')) {
                $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                foreach ($_nameAfterChildren as $_nameAfterChildName) {
                    $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                    $_nameAfterChild->setProduct($_product);
                    echo $_nameAfterChild->toHtml();
                }
            }
          </div>
          */ ?>
      </div>
    <?php endforeach; ?>
  </div>
</div>

<script type="text/javascript">
//<![CDATA[

  jQuery('#bestselling-products').slick({
    dots: false,
    infinite: true,
    slidesToShow: 4,
    slidesToScroll: 1,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3
        }
      },
      {
        breakpoint: 768,
        settings: {
          slidesToShow: 2
        }
      }
    ]
  })

//]]>
</script>
<?php endif ?>
