<?php
  $_helper = $this->helper('catalog/output');
  $products = $this->getProductCollection();
?>
<?php if($products && count($products)): ?>
<div class="box-collateral">
  <div id="bestselling-products">
    <?php foreach ($products as $_product): ?>
      <?php $manufacturer = $_product->getAttributeText('manufacturer'); ?>

      <div class="bestseller-product productlist-element">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
          <img id="product-collection-image-<?php echo $_product->getId(); ?>"
            src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(232,245); ?>" width="232" height="245"
            alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
        </a>
        <div class="product-info">
          <div class="product-list-details left">
            <div class="product-manufacturer"><?php echo ($manufacturer != '' ? $manufacturer : '&nbsp;'); ?></div>
            <div class="product-name">
              <?php $productname = $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
              <?php echo Mage::helper("horsebrands_rewrites")->getShortProductname($productname); ?>
            </div>
          </div>
          <div class="product-list-price right">
            <div class="product-price">
              <?php echo $this->getPriceHtml($_product, true) ?>
            </div>
          </div>
        </div>
          <?php
          // Provides extra blocks on which to hang some features for products in the list
          // Features providing UI elements targeting this block will display directly below the product name
          if ($this->getChild('name.after')) {
              $_nameAfterChildName = 'product_list.swatches';
              if ($_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName)) {
                echo '<div class="offcanvas offcanvas-left">';
                $_nameAfterChild->setProduct($_product);
                echo $_nameAfterChild->toHtml();
                echo '</div>';
              }
          }
          ?>
      </div>
    <?php endforeach; ?>
  </div>
</div>

<script type="text/javascript">
//<![CDATA[

  jQuery('#bestselling-products').slick({
    dots: false,
    infinite: true,
    slidesToShow: 4,
    slidesToScroll: 1,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3
        }
      },
      {
        breakpoint: 768,
        settings: {
          slidesToShow: 2
        }
      }
    ]
  })

//]]>
</script>
<?php endif ?>
