<?php
  $_helper = $this->helper('catalog/output');
  $skus = explode(",", $this->getData('product_skus'));
  $products = null;
  $category = Mage::getModel('catalog/category')->load(114);

  if($skus && count($skus)>0) {
    $products = Mage::getResourceModel('catalog/product_collection')
                  ->addAttributeToSelect('*')
                  ->addAttributeToFilter('sku', array( 'in' => $skus ))
                  ->addCategoryFilter($category)
                  ->load();
  }
?>
<?php if(count($products)): ?>
<div class="box-collateral">
  <div id="featured-products">
    <?php foreach ($products as $_product): ?>
      <div class="featured-product">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
          <img id="product-collection-image-<?php echo $_product->getId(); ?>"
            src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(232,245); ?>" width="232" height="245"
            alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
        </a>
        <div class="product-info">
          <div class="product-list-details left">
            <div class="product-manufacturer"><?php echo ($manufacturer != '' ? $manufacturer : '&nbsp;'); ?></div>
            <div class="product-name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></div>
          </div>
          <div class="product-list-price right">
            <?php if($_product->getFinalPrice() != $_product->getPrice()): ?>
              <div class="product-price old"><?php echo Mage::helper('core')->currency($_product->getPrice(),true,false); ?></div>
            <?php endif; ?>
            <div class="product-price"><?php echo Mage::helper('core')->currency($_product->getFinalPrice(),true,false); ?></div>
          </div>
        </div>
          <?php /*
          // Provides extra blocks on which to hang some features for products in the list
          // Features providing UI elements targeting this block will display directly below the product name
          if ($this->getChild('name.after')) {
              $_nameAfterChildName = 'product_list.swatches';
              if ($_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName)) {
                echo '<div class="offcanvas offcanvas-left">';
                $_nameAfterChild->setProduct($_product);
                echo $_nameAfterChild->toHtml();
                echo '</div>';
              }
          }
          ?>
          <div class="offcanvas offcanvas-bottom">
            foundation badges <?php echo 'saleable: ' . ($_product->isSaleable() ? 'true' : 'false') ?>
            <?php
            // Provides extra blocks on which to hang some features for products in the list
            // Features providing UI elements targeting this block will display directly below the product name
            if (false && $this->getChild('name.after')) {
                $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                foreach ($_nameAfterChildren as $_nameAfterChildName) {
                    $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                    $_nameAfterChild->setProduct($_product);
                    echo $_nameAfterChild->toHtml();
                }
            }
          </div>
          */ ?>
      </div>
    <?php endforeach; ?>
  </div>
</div>

<script type="text/javascript">
//<![CDATA[

  jQuery('#featured-products').slick({
    dots: false,
    infinite: true,
    slidesToShow: 4,
    slidesToScroll: 1,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3
        }
      },
      {
        breakpoint: 768,
        settings: {
          slidesToShow: 2
        }
      }
    ]
  })

//]]>
</script>
<?php endif ?>
