<?php $_helper = $this->helper('catalog/output'); ?>
<?php $upsellitems = $this->getItemCollection()->getItems() ?>

<?php if(count($upsellitems)): ?>
<div class="row smaller-margins full-width crossselling-container">
  <div class="columns medium-12">
    <section class="upsell-products-wrapper">
      <h5 class="section-title"><?php echo $this->__('You may also be interested in the following product(s)') ?></h5>
      <div class="box-up-sell">
        <div id="featured-products">
          <?php foreach ($upsellitems as $_product): ?>
            <div class="featured-product">
              <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                  src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(232,245); ?>" width="232" height="245"
                  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
              </a>
              <div class="product-info">
                <div class="top-row">
                  <h3><?php echo ($_product->getManufacturer() ? $_product->getAttributeText('manufacturer') : '&nbsp;'); ?></h3>
                  <?php $_msrp = $_helper->productAttribute($_product, $_product->getMsrp(), 'msrp') ?>
                  <?php $_msrpPrice = $this->helper('core')->currency($_msrp,true,true) ?>
                  <?php if($_msrp): ?>
                    <span class="msrp"><?php echo $_msrpPrice; ?></span>
                  <?php endif; ?>
                </div>
                <div class="bottom-row">
                  <span class="product-name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></span>
                  <span class="price"><?php echo Mage::helper('core')->currency($_product->getFinalPrice(),true,false); ?></span>
                </div>
              </div>
                <?php
                if ($this->getChild('name.after')) {
                    $_nameAfterChildName = 'product_list.swatches';
                    if ($_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName)) {
                      echo '<div class="offcanvas offcanvas-left">';
                      $_nameAfterChild->setProduct($_product);
                      echo $_nameAfterChild->toHtml();
                      echo '</div>';
                    }
                }
                ?>
            </div>
          <?php endforeach; ?>
        </div>

      </div>
    </section>
  </div>
</div>
<script type="text/javascript">
//<![CDATA[

  jQuery('#featured-products').slick({
    dots: false,
    infinite: true,
    slidesToShow: 4,
    slidesToScroll: 1,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3
        }
      },
      {
        breakpoint: 768,
        settings: {
          slidesToShow: 2
        }
      }
    ]
  })

//]]>
</script>
<?php endif; ?>
