<?php $columns = $this->getColumns(); ?>
<table class="clean-table linearize-table" id="wishlist-table">
    <thead>
        <tr>
            <?php
              $i = 0;
                /* @var $column Mage_Wishlist_Block_Customer_Wishlist_Item_Column */
                foreach ($columns as $column):
                    $_blockName = str_replace('.','-',strtolower($column->getNameInLayout()));
            ?>

                <th class="<?php echo $_blockName; ?>"<?php echo ($i==0 ? 'colspan="2"' : '')?>><?php echo $column->getTitle();?></th>
                <?php $i++; ?>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <?php if (count($this->getItems())): ?>
            <?php foreach ($this->getItems() as $item): ?>
                <tr id="item_<?php echo $item->getId();?>">
                    <?php
                        foreach ($columns as $key => $column):
                            $_blockName = str_replace('.','-',strtolower($column->getNameInLayout()));

                            /* Override default column title in layout, useful for certain cases like select all box */
                            if ($column->getRwdTitle()) {
                                $_rwdLabel = $column->getRwdTitle();
                            } else {
                                $_rwdLabel = ($column->getTitle()) ? $column->getTitle() : false;
                            }
                    ?>
                        <?php $column->setItem($item); echo $column->toHtml($item);?>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach ?>
        <?php else: ?>
            <td colspan="<?php echo count($columns);?>" class="wishlist-empty"><?php echo $this->__('This Wishlist has no Items');?></td>
        <?php endif; ?>
    </tbody>
</table>
<?php foreach ($columns as $column): ?>
    <?php echo $column->getAdditionalHtml();?>
<?php endforeach; ?>
<script type="text/javascript">
//<![CDATA[
    decorateTable('wishlist-table');

<?php foreach ($columns as $column): ?>
    <?php echo $column->getJs();?>
<?php endforeach; ?>
//]]>
</script>
