<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_category = (mage::registry('current_category') ? mage::registry('current_category') : null);

    $advHelper = Mage::helper('horsebrands_rewrites/adventskalender');
    $_isAdvCategory = false;

    if($_category) {
      $productpositions = $_category->getProductsPosition();
      $_isAdvCategory = $advHelper->isAdvEnabled($_category->getId());
    }

    $_toolbar = $this->getToolbarBlock();
?>
<div class="category-products">
  <?php if(false && $_category): ?>
    <h3>
      <?php echo $_category->getName(); ?>
    </h3>
  <?php endif; ?>

<?php echo $this->getChildHtml('catalog.filter') ?>

<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php //echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
      <?php // no no list mode... - list mode not here ?>
    <?php else: ?>
    <?php // Grid Mode ?>

    <?php $gridSize = 3; ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
      <?php $i++ ?>
      <!-- if($_item->getProduct()->getData('manufacturer')) { $manufacturer = $_item->getProduct()->getAttributeText('manufacturer'); } -->
      <?php $manufacturer = $_product->getAttributeText('manufacturer'); ?>

      <?php $firstInRow = ($i % $gridSize == 1) ?>
      <?php $lastInRow = ($i % $gridSize == 0) ?>
      <?php $lastInCollection = ($i == $_collectionSize) ?>

      <?php // new row? ?>
      <?php if($firstInRow): ?>
        <div class="row full-width smaller-margins products-row">
      <?php endif ?>
          <div class="columns medium-4<?php echo ($lastInCollection ? ' end' : ''); ?>">
            <div class="productlist-element item <?php echo $_product->getTypeId() ?>">
              <?php if($_isAdvCategory): ?>
                <?php $position = $productpositions[$_product->getId()]; ?>
                <?php if($advHelper->isAdvDoorClosed($position)): ?>
                  <div class="out-of-stock-overlay" style="background-color: #fff;">
                    <div <?php echo $advHelper->getDoorClosedStyle($position) ?>>&nbsp;</div>
                  </div>
                <?php elseif(!$_product->isSaleable()): ?>
                  <div class="out-of-stock-overlay">
                    <div class="out-of-stock-text">Ausverkauft</div>
                  </div>
                <?php endif; ?>
              <?php elseif(!$_product->isSaleable()): ?>
                <div class="out-of-stock-overlay">
                  <div class="out-of-stock-text">Ausverkauft</div>
                </div>
              <?php endif; ?>
              <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php $_imgSize = 210; ?>
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                   src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(480,510); ?>" width="100%" height="255"
                   alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
               <div class="product-info">
                 <div class="product-list-details left">
                   <div class="product-manufacturer"><?php echo ($manufacturer != '' ? $manufacturer : '&nbsp;'); ?></div>
                   <div class="product-name">
                     <?php $productname = $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                     <?php echo Mage::helper("horsebrands_rewrites")->getShortProductname($productname); ?>
                   </div>
                 </div>
                 <div class="product-list-price right">
                   <div class="product-price">
                     <?php if($_product->isSaleable()): ?>
                      <?php echo $this->getPriceHtml($_product, true) ?>
                     <?php endif; ?>
                   </div>
                 </div>
               </div>
              </a>
              <?php
              // Provides extra blocks on which to hang some features for products in the list
              // Features providing UI elements targeting this block will display directly below the product name
              if ($this->getChild('name.after')) {
                  $_nameAfterChildName = 'product_list.swatches';
                  if ($_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName)) {
                    echo '<div class="offcanvas offcanvas-left">';
                    $_nameAfterChild->setProduct($_product);
                    echo $_nameAfterChild->toHtml();
                    echo '</div>';
                  }
              }
              ?>
              <div class="offcanvas offcanvas-bottom">
                foundation badges <?php echo 'saleable: ' . ($_product->isSaleable() ? 'true' : 'false') ?>
                <?php
                // Provides extra blocks on which to hang some features for products in the list
                // Features providing UI elements targeting this block will display directly below the product name
                if (false && $this->getChild('name.after')) {
                    $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                    foreach ($_nameAfterChildren as $_nameAfterChildName) {
                        $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                        $_nameAfterChild->setProduct($_product);
                        echo $_nameAfterChild->toHtml();
                    }
                }
                ?>
              </div>
            </div>
          </div>
        <?php // close row? ?>
        <?php if ($lastInRow || $lastInCollection): ?>
          </div>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
<?php endif; ?>
</div>

<script>
  $j(window).load(function() {
    var parent = $j('div.offcanvas.offcanvas-left').parent('.productlist-element');
    var element = $j('div.offcanvas.offcanvas-left');

    element.height(parent.height() - 2);
  });
</script>
