<div class="giftcard-banner">
  <img src="http://placehold.it/1100x300" alt="dong." />
</div>
<div class="choose-theme-wrapper">
  <div class="box">
    <h2 class="title">Wähle ein Gutschein-Motiv aus</h2>
    <div class="content">
      Motive.
    </div>
  </div>
</div>
<div class="personalize-giftcard-wrapper">
  <div class="box">
    <h2 class="title">Personalisiere deinen Gutschein</h2>
    <div class="content">
      Personalisierung.
    </div>
  </div>
</div>
<div class="personalize-giftcard-wrapper">
  <div class="box">
    <h2 class="title">Wähle die gewünschte Versandart</h2>
    <div class="content">
      Zum Ausdrucken und so.
    </div>
  </div>
</div>
