<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" class="img-responsive full-width" />';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<div class="deinverein-category-banner">
  <div class="banner-overlay centered">
    <img src="<?php echo $_category->getImageUrl() ?>" alt="deinverein-logo" />
  </div>
</div>

<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
  <div class="deinverein-category-description">
    <p>
      <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
    </p>
  </div>
<?php endif; ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php
      $block = $this->getLayout()->getBlock('product_list');
      $block->setIsShowHeadline(false);
      echo $block->toHtml();
      // echo $this->getProductListHtml()
    ?>
<?php endif; ?>
