 <ul class="unstyled">
<?php foreach ($this->getItems() as $_item): ?>
    <li>
      <?php if ($_item->getCount() > 0): ?>
        <a class="expand" href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
          <?php echo $_item->getLabel() ?>
          <?php echo ($this->shouldDisplayProductCount() ? ' ('.$_item->getCount().')' : ''); ?>
        </a>
      <?php endif; ?>
    </li>
<?php endforeach ?>
</ul>
