 <ul class="unstyled">
<?php foreach ($this->getItems() as $_item): ?>
    <li>
      <?php if ($_item->getCount() > 0): ?>
        <a class="expand" href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
          <?php echo $_item->getLabel() ?>
          <?php echo ($this->shouldDisplayProductCount() ? ' ('.$_item->getCount().')' : ''); ?>
        </a>
        <?php //else: echo $_item->getLabel() ?>
      <?php endif; ?>
    </li>
<?php endforeach ?>
</ul>
<?php /*
<ol>
<?php foreach ($this->getItems() as $_item): ?>
    <li>
        <?php if ($_item->getCount() > 0): ?>
        <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
      <?php else: echo $_item->getLabel() ?>
        <?php endif; ?>
        <?php if ($this->shouldDisplayProductCount()): ?>
        (<?php echo $_item->getCount() ?>)
        <?php endif; ?>
    </li>
<?php endforeach ?>
</ol>
*/ ?>
