<?php
/**
 * Category layered navigation state
 *
 * @see Mage_Catalog_Block_Layer_State
 */
?>

<?php $_filters = $this->getActiveFilters() ?>
<?php if(!empty($_filters)): ?>
  <ul class="unstyled inline selected-filter" style="float: left;">
    <?php foreach ($_filters as $_filter): ?>
        <li>
          <a href="<?php echo $_filter->getRemoveUrl() ?>" class="btn btn-transparent gray-light no-radius">
            <?php echo $this->stripTags($_filter->getLabel()) ?> <i class="fa fa-times"></i>
          </a>
        </li>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>
