<div class="layered-navigation-wrapper">
  <?php if($this->canShowOptions()): ?>
  <div class="available-filter-wrapper">
    <!-- for schleife, 3 spalten -->
    <?php $_filters = $this->getFilters() ?>

    <?php $gridSize = 3; ?>
    <?php $_collectionSize = count($_filters) - count($this->getLayer()->getState()->getFilters()) -1; ?>

    <?php $rowOpen = false; ?>
    <?php $i=0; foreach ($_filters as $_filter): ?>
    <?php if($_filter->getItemsCount()): ?>
      <?php $firstInRow = ( $i%$gridSize == 0 ); ?>
      <?php $lastInRow = ( $i%$gridSize == $gridSize-1 ); ?>
      <?php $lastInCollection = ($i==$_collectionSize); $i++ ?>
      <?php // new row? ?>
      <?php if($firstInRow): ?>
        <?php $rowOpen = true; ?>
        <div class="row full-width smaller-margins products-row">
      <?php endif ?>
          <div class="columns medium-4<?php echo ($lastInCollection ? ' end' : ''); ?>">
            <button class="filter-dropdown expand" onclick="toggleFilter(this);">
              <?php echo $this->__($_filter->getName()) ?> <i class="fa fa-angle-down"></i>
              <div class="filter-dropdown-content"><?php echo $_filter->getHtml() ?></div>
            </button>
          </div>
      <?php // close row? ?>
      <?php if ($lastInRow || $lastInCollection): ?>
        <?php $rowOpen = false; ?>
        </div>
      <?php endif ?>

    <?php endif; ?>
    <?php endforeach; ?>

    <?php if($rowOpen): ?>
      <?php //pseudo element if, $i is not a multiple of 4, and close row ?>
        <?php if($i%$gridSize != 0): ?>
          <div class="columns medium-4 end"></div>
        <?php endif; ?>
      <!-- </div> -->
    <?php endif; ?>
  </div>
  <?php endif; ?>
  <?php if ($this->getLayer()->getState()->getFilters()): ?>
    <div class="selected-filter-wrapper clearfix" style="">
      <?php echo $this->getStateHtml() ?>
      <div class="button-wrapper" style="float:right;">
        <a class="button button-transparent" href="<?php echo $this->getClearUrl() ?>">Alle Filter l&ouml;schen<?php //echo $this->__('Clear All') ?></a>
      </div>
    </div>
  <?php endif; ?>

</div>

<script>
  function toggleFilter(button) {
    if($j(button).children('div.filter-dropdown-content').is(':visible')) {
      $j(button).css('z-index', 0);
    } else {
      $j(button).css('z-index', 100);
    }
    $j(button).children('div.filter-dropdown-content').toggle();
  }
  $j(window).load(function() {
    $j("div.btn.filter-dropdown").click(function(e) {
      if($j(this).children('div.filter-dropdown-content').is(':visible')) {
        $j(this).css('z-index', 0);
      } else {
        $j(this).css('z-index', 100);
      }
      $j(this).children('div.filter-dropdown-content').toggle();
    });
  });
</script>
