<header>
  <div class="fixed-top">
    <div class="container">
      <span>Kostenlose Hotline</span>
      <span>service@horsebrands.de</span>
      <span>14 Tage Rückgaberecht</span>
      <span>Versandkostenfrei ab einem Bestellwert von 30€</span>
    </div>
  </div>
  <div class="top-header container clearfix">
    <div class="top-header-element top-header-left store-select" style="display:none;">
    </div>
    <div class="top-header-element top-header-center brand">
      <a href="<?php echo $this->getBaseUrl() ?>" class="logo-link">
        <img src="<?php echo $this->getSkinUrl('images/logo.png') ?>" class="img-responsive">
      </a>
    </div>
    <div class="top-header-element top-header-right customer-nav" style="display:none;">
    </div>
</header>
