<script type="text/javascript">
//<![CDATA[
var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
var lastPrice;
//]]>
</script>
<form action="" id="co-payment-form">
  <div class="fieldset">
    <?php echo $this->getChildChildHtml('methods_additional', '', true, true) ?>
    <?php echo $this->getChildHtml('methods') ?>
  </div>
</form>
<div class="grand_total_overview clearfix">
  <dl class="totals-block">
    <dt class="totals-strong">
      <?php echo $this->__('Grand Total') ?>:
      <p class="note"><?php echo $this->__('incl. VAT and Shipping') ?></p>
    </dt>
    <dd class="totals-strong">
      <?php echo $this->helper('checkout')->formatPrice( Mage::getModel('checkout/session')->getQuote()->getGrandTotal() ); ?>
    </dd>
  </dl>
</div>
<?php echo $this->getChildChildHtml('additional') ?>
<div class="buttons-set clearfix" id="payment-buttons-container">
  <button class="opc-next-button gold right" onclick="payment.save();"><?php echo $this->__('Continue'); ?></button>
  <div class="fineprint-container" style="clear: both; float: right;">
    <p>Bestellung im nächsten Schritt überprüfen und absenden</p>
  </div>
  <span class="please-wait" id="payment-please-wait" style="display:none;">
    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
  </span>
</div>
<script type="text/javascript">
//<![CDATA[
function toggleToolTip(event){
  if($('payment-tool-tip')){
    $('payment-tool-tip').setStyle({
      top: (Event.pointerY(event)-560)+'px'//,
      //left: (Event.pointerX(event)+100)+'px'
    })
    $('payment-tool-tip').toggle();
  }
  Event.stop(event);
}
if($('payment-tool-tip-close')){
  Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
}
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
//]]>
</script>
