<?php /* ?>
<div class="block block-progress opc-block-progress<?php if (!$this->isCustomerLoggedIn()/* && !$this->getCheckout()->getStepData('billing', 'is_show')* /): ?> opc-block-progress-step-login<?php endif; ?>">
    <div class="block-title">
        <strong><span><?php echo $this->__('Your Checkout Progress') ?></span></strong>
    </div>
    <div class="block-content">
        <dl>
            <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
            <div id="billing-progress-opcheckout">
                <?php echo $this->getChildHtml('billing.progress') ?>
            </div>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
            <div id="shipping-progress-opcheckout">
                <?php echo $this->getChildHtml('shipping.progress') ?>
            </div>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
            <div id="shipping_method-progress-opcheckout">
                <?php echo $this->getChildHtml('shippingmethod.progress') ?>
            </div>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
            <div id="payment-progress-opcheckout">
                <?php echo $this->getChildHtml('payment.progress') ?>
            </div>
            <?php endif; ?>
        </dl>
    </div>
</div>
*/ ?>
<div class="block block-progress opc-block-progress<?php if (!$this->isCustomerLoggedIn()/* && !$this->getCheckout()->getStepData('billing', 'is_show')*/): ?> opc-block-progress-step-login<?php endif; ?>">

    <ul class="unstyled inline same-width-full">
      <li class="step-login <?php echo (!$this->isCustomerLoggedIn() ? 'active' : '') ?>">
        <i class="fa fa-lock"></i> Sichere Verbindung
      </li>

      <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
      <li id="billing-progress-opcheckout" class="step-address">1. Adresse</li><?php //echo $this->getChildHtml('billing.progress') ?>
      <?php endif; ?>

      <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
      <li id="payment-progress-opcheckout" class="step-payment">2. Zahlart</li><?php //echo $this->getChildHtml('payment.progress') ?>
      <?php endif; ?>
      <li id="review-progress-opcheckout" class="step-review">3. Best&auml;tigen</li>
    </ul>

</div>
