<div class="box">
  <h2 class="title"><?php echo $this->__('Available Shipping Methods'); ?></h2>
  <div class="content clearfix">
    <form id="co-shipping-method-form" action="">
        <div id="checkout-shipping-method-load">
           <!-- Content loaded dynamically -->
        </div>
        <script type="text/javascript">
        //<![CDATA[
            var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
        //]]>
        </script>
        <div id="onepage-checkout-shipping-method-additional-load">
            <?php //echo $this->getChildHtml('additional') ?>
        </div>
        <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </form>
  </div>
</div>
<div class="buttons-set clearfix" id="shipping-method-buttons-container">
  <button class="left" onclick="checkout.back();"><i class="fa fa-angle-double-left"></i> <?php echo $this->__('Back'); ?></button>
  <button class="gold right" onclick="shippingMethod.save();"><?php echo $this->__('Continue'); ?> <i class="fa fa-angle-double-right"></i></button>
</div>
