<div class="box">
  <h2 class="title"><?php echo $this->__('Shipping Address'); ?></h2>
  <div class="content clearfix">
    <!-- <form id="co-shipping-form" action=""> -->
      <?php if (false && $this->customerHasAddresses()): ?>
         <li class="wide">
             <label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
             <div class="input-box">
                 <?php echo $this->getAddressesHtmlSelect('shipping') ?>
             </div>
         </li>
      <?php endif ?>
      <p id="same-as-billing-text">
        <?php echo $this->__('Same as Billing Address'); ?>
      </p>
      <div id="shipping-address-form" class="scaffold-form" style="display: none">
        <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>
        <div class="kv">
          <div class="key">
            <label><?php echo $this->__('c/o'); ?></label>
          </div>
          <div class="value">
            <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" onchange="shipping.setSameAsBilling(false);" />
          </div>
        </div>
        <div class="kv">
          <div class="key">
            <label><?php echo $this->__('Street'); ?><em>*</em></label>
          </div>
          <div class="value">
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
            <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
              <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
            <?php endfor; ?>
          </div>
        </div>
        <div class="kv">
          <div class="key">
            <label><?php echo $this->__('Post Code'); ?><em>*</em></label>
          </div>
          <div class="value">
            <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onchange="shipping.setSameAsBilling(false);" />
          </div>
        </div>
        <div class="kv">
          <div class="key">
            <label><?php echo $this->__('City'); ?><em>*</em></label>
          </div>
          <div class="value">
            <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
          </div>
        </div>
        <div class="kv">
          <div class="key">
            <label><?php echo $this->__('Country'); ?><em>*</em></label>
          </div>
          <div class="value">
            <?php echo $this->getCountryHtmlSelect('shipping') ?>
          </div>
        </div>
        <div class="kv">
          <div class="key">
            <label for="shipping:telephone"><?php echo $this->__('Telephone') ?><em>*</em></label>
          </div>
          <div class="value">
            <input type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" />
          </div>
        </div>
        <input type="hidden" name="shipping[save_in_address_book]" value="1" />
  </div>
</div>
<script type="text/javascript">
//<![CDATA[
    // var shipping = new Shipping('co-address-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>');
    // var shippingForm = new VarienForm('co-address-form');
    // shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Select State/Province...')) ?>');
    // $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    // var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
//]]>
</script>
