<?php
/**
 * Product description template
 *
 * @see Mage_Catalog_Block_Product_View_Description
 */
?>
<?php $_shortDescription = $this->getProduct()->getShortDescription(); ?>
<?php $_description = $this->getProduct()->getDescription(); ?>
<section class="product-description">
  <h5 class="section-title">Produktbeschreibung</h5>

  <p class="productname">
    <strong><?php echo $this->getProduct()->getName(); ?></strong>
  </p>

  <?php if ($_shortDescription): ?>
  <p class="productdescription">
    <?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $_shortDescription, 'shortDescription') ?>
  </p>
  <p id="desc" class="productdescription hide">
      <?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $_description, 'description') ?>
  </p>
  <a id="productdesc-continue-reading" class="btn continue-reading vertical">
    <div>Weiter lesen</div><i class="fa fa-angle-double-down"></i>
  </a>

  <script>
    $j('#productdesc-continue-reading').click(function(event) {
      $j('#desc').toggle();

      if($j('#desc').is(':visible')) {
        $j('#productdesc-continue-reading div').html('&nbsp;');
        $j('#productdesc-continue-reading i.fa').removeClass('fa-angle-double-down').addClass('fa-angle-double-up')
      } else {
        $j('#productdesc-continue-reading div').html('Weiter lesen');
        $j('#productdesc-continue-reading i.fa').removeClass('fa-angle-double-up').addClass('fa-angle-double-down')
      }
    });
  </script>

  <?php elseif ($_description && false): ?>
  <p class="productdescription">
      <?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $_description, 'description') ?>
  </p>
  <?php endif; ?>
</section>
