<?php
/**
 * Product description template
 *
 * @see Mage_Catalog_Block_Product_View_Description
 */
?>
<?php $_shortDescription = $this->getProduct()->getShortDescription(); ?>
<?php $_description = $this->getProduct()->getDescription(); ?>
<section class="product-description">
  <h5 class="section-title">Produktbeschreibung</h5>

  <p class="productname">
    <strong><?php echo $this->getProduct()->getName(); ?></strong>
  </p>

  <?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $_description, 'description') ?>
</section>
