<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<div class="product-image product-image-zoom">
    <div class="product-image-gallery">
        <img id="image-main"
             class="gallery-image visible"
             src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>"
             alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>"
             title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" />

        <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
            <?php if ($this->isGalleryImageVisible($_image)): ?>
            <img id="image-<?php echo $i; ?>"
                 class="gallery-image"
                 src="<?php echo $this->getGalleryImageUrl($_image); ?>"
                 data-zoom-image="<?php echo  $this->getGalleryImageUrl($_image); ?>" />
            <?php endif; ?>
        <?php $i++; endforeach; ?>
    </div>
</div>

<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
  <div id="more-views-gallery" class="product-image-thumbs">
  <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
      <?php if ($this->isGalleryImageVisible($_image)): ?>
      <div class="more-views-gallery-element">
          <a class="thumb-link" href="#" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>" data-image-index="<?php echo $i; ?>">
              <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(75); ?>"
                   width="75" height="75" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
          </a>
      </div>
      <?php endif; ?>
  <?php $i++; endforeach; ?>
  </div>
</div>
<?php endif; ?>

<script type="text/javascript">
//<![CDATA[
  jQuery(document).ready(function($) {
    $('#more-views-gallery').slick({
      dots: false,
      infinite: false,
      slidesToShow: 4,
      slidesToScroll: 1,
      centerMode: true,
      variableWidth: true
    });
  });
//]]>
</script>

<?php echo $this->getChildHtml('after'); ?>
