<script type="text/javascript">
//<![CDATA[
    i=0;
    var recipCount  = 1;
    var maxRecip    = <?php echo $this->getMaxRecipients() ?>;
    function remove_recipient(i){
        $('recipients_name'+i).up(2).remove();
        recipCount--;
        if(recipCount<maxRecip && maxRecip != 0) {
            $('add_recipient_button').show();
            $('max_recipient_message').hide();
        }
        return false;
    }

    function add_recipient(){
        ul = $('recipients_options');
        var li_mail = Element.extend(document.createElement("LI"));
        li_mail.addClassName('fields additional-row');
        li_mail.innerHTML = '<p style="margin-bottom: 0; text-align: right;"><a href="delete_email" title="<?php echo $this->jsQuoteEscape($this->__('Remove Recipient')) ?>" onclick="remove_recipient('+i+'); return false" class="btn-remove"><?php echo $this->jsQuoteEscape($this->__('Remove')) ?> <i class="fa fa-times"></i><\/a><\/p>'
        li_mail.innerHTML += '<div class="field"><label for="recipients_name'+i+'" class="required"><em>*<\/em><?php echo $this->jsQuoteEscape($this->__('Name:')) ?><\/label><div class="input-box"><input name="recipients[name][]" type="text" class="input-text required-entry" id="recipients_name'+i+'" /><\/div>';
        li_mail.innerHTML += '<div class="field"><label for="recipients_email'+i+'" class="required"><em>*<\/em><?php echo $this->jsQuoteEscape($this->__('Email Address:')) ?><\/label><div class="input-box"><input name="recipients[email][]" value="" title="<?php echo $this->jsQuoteEscape($this->__('Email Address')) ?>" id="recipients_email'+i+'" type="text" class="input-text required-entry validate-email" /><\/div><\/div>';
        i++;
        recipCount++;
        if(recipCount>=maxRecip && maxRecip != 0) {
            $('add_recipient_button').hide();
            $('max_recipient_message').show();
        }

        ul.appendChild(li_mail);
    }
//]]>
</script>

<?php $_product = Mage::getModel('catalog/product')->load($this->getProductId()); ?>
<?php $manufacturer = $_product->getAttributeText('manufacturer'); ?>
<?php $_helper = $this->helper('catalog/output'); ?>

<div class="send-friend">
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <p class="back-link"><a href="#" onclick="history.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <div class="row">
      <div class="columns small-12 medium-5">
        <div class="product-info-wrapper">
          <a href="<?php echo $_product->getProductUrl() ?>">
            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
               src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(480,510); ?>" class="img-responsive"
               alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" />
             <div class="product-info">
               <div class="top-row">
                 <div class="product-manufacturer"><?php echo ($manufacturer != '' ? $manufacturer : '&nbsp;'); ?></div>
                 <div class="product-price"><?php echo Mage::helper('core')->currency($_product->getFinalPrice(),true,false); ?></div>
               </div>
               <div class="bottom-row">
                 <div class="product-name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></div>
               </div>
             </div>
            </a>

        </div>
      </div>
      <div class="columns small-12 medium-7">
        <form action="<?php echo $this->getSendUrl() ?>" method="post" id="product_sendtofriend_form">
          <?php echo $this->getBlockHtml('formkey')?>
          <div class="box">
            <h2 class="title"><?php echo $this->__('Sender') ?></h2>
            <div class="content">
              <ul class="form-list unstyled" id="sender_options">
                <li class="fields">
                    <div class="field">
                        <label for="sender_name" class="required"><?php echo $this->__('Name') ?><em>*</em></label>
                        <div class="input-box">
                            <input name="sender[name]" value="<?php echo $this->escapeHtml($this->getUserName()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Name')) ?>" id="sender_name" type="text" class="input-text required-entry" />
                        </div>
                    </div>
                    <div class="field">
                       <label for="sender_email" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
                       <div class="input-box">
                           <input name="sender[email]" value="<?php echo $this->escapeHtml($this->getEmail()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" id="sender_email" type="text" class="input-text required-entry validate-email" />
                       </div>
                    </div>
                </li>
                <li class="wide">
                    <label for="sender_message" class="required"><?php echo $this->__('Message') ?><em>*</em></label>
                    <div class="input-box">
                        <textarea name="sender[message]" class="input-text required-entry" id="sender_message" cols="3" rows="3"><?php echo $this->escapeHtml($this->getMessage())?></textarea>
                    </div>
                </li>
              </ul>
            </div>
          </div>
          <div class="box">
            <h2 class="title"><?php echo $this->__('Recipient') ?></h2>
            <div class="content">
              <ul class="form-list unstyled" id="recipients_options">
                <li class="fields">
                    <div class="field">
                        <label for="recipients_name" class="required"><?php echo $this->__('Name') ?><em>*</em></label>
                        <div class="input-box">
                            <input name="recipients[name][]" type="text" class="input-text required-entry" id="recipients_name" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="recipients_email" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
                        <div class="input-box">
                            <input name="recipients[email][]" value="" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" id="recipients_email" type="text" class="input-text required-entry validate-email" />
                        </div>
                    </div>
                </li>
              </ul>
              <div class="add-recipient-wrapper">
                <?php if (1 < $this->getMaxRecipients()): ?>
                  <button type="button" onclick="add_recipient();" class="button white"><span><span><?php echo $this->__('Add Recipient') ?></span></span></button>
                <?php endif; ?>
              </div>
            </div>
          </div>
          <div class="buttons-set">
            <button type="submit" class="button gold right<?php if (!$this->canSend()):?> disabled<?php endif ?>"<?php if (!$this->canSend()):?> disabled="disabled"<?php endif ?>><span><span><?php echo $this->__('Send Email') ?></span></span></button>
          </div>
        </form>
      </div>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var productSendtofriendForm = new VarienForm('product_sendtofriend_form');
        productSendtofriendForm.submit = function() {
            if(this.validator.validate()) {
                this.form.submit();
            }
        }.bind(productSendtofriendForm);
    //]]>
    </script>
</div>
