<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" class="img-responsive full-width" />';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>

  <?php if($_description=$this->getCurrentCategory()->getDescription() && false): ?>
    <div class="category-description std">
        <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
    </div>
  <?php endif; ?>

  <h3><?php echo $_category->getName(); ?></h3>
  
  <?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
  <?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>
  <?php else: ?>
    <?php echo $this->getProductListHtml() ?>
  <?php endif; ?>
