<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" class="img-responsive full-width" />';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<!-- <div class="page-title category-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
</div> -->

<?php echo $this->getMessagesBlock()->toHtml() ?>

  <?php if($_imgUrl): ?>
    <div class="category-headline">
      <article class="teaser-element">
        <div class="canvas">
          <div class="crop-height">
            <?php echo $_imgHtml ?>
          </div>
        </div>
        <div class="title">
          <?php echo $_category->getName(); ?>
        </div>
      </article>
    </div>
  <?php endif; ?>
  <?php if($_category->hasChildren()): ?>
    <?php $subcategories = $_category->getChildrenCategories(); ?>
    <?php $subcatCount = $subcategories->getSize(); ?>
    <?php $i = 1; ?>
    <?php foreach ($_category->getChildrenCategories() as $subcat): ?>
      <?php $mediumFirst = ($i % 3 == 1 ? true : false)?>
      <?php $mediumLast = ($i % 3 == 0 ? true : false)?>
      <?php $last = ($i == $subcatCount ? ' end' : '')?>

      <?php echo ($mediumFirst ? '<div class="row full-width smaller-margins">' : ''); ?>

      <?php $imgHtml = '<img src="'.$subcat->getImageUrl().'" alt="'.$this->escapeHtml($subcat->getName()).'" title="'.$this->escapeHtml($subcat->getName()).'" class="img-responsive" />'; ?>
      <div class="columns medium-4<?php echo $last ?>">
        <article class="teaser-element">
          <div class="canvas">
            <div class="crop-height">
              <!-- <?php echo $imgHtml ?>  -->
              <?php echo ($subcat->getImageUrl() != '' ? $imgHtml : '<img src="http://placehold.it/233x220" class="img-responsive" />'); ?>
            </div>
          </div>
          <div class="btn-container">
            <a class="btn small-height btn-transparent gray expand"><?php echo $subcat->getName(); ?> &gt;</a>
          </div>
        </article>
      </div>

      <?php echo ($mediumLast ? '</div>' : ''); ?>
      <?php $i++ ?>
    <?php endforeach; ?>
    </div>
  <?php endif; ?>

<?php if($_description=$this->getCurrentCategory()->getDescription() && false): ?>
    <div class="category-description std">
        <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
    </div>
<?php endif; ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
