<div class="page-title">
    <h1><?php echo $this->__('Edit Account Information') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" autocomplete="off" id="form-validate" class="scaffold-form" enctype="multipart/form-data">
  <?php echo $this->getBlockHtml('formkey')?>
    <div class="row">
      <div class="columns small-12 medium-6">
        <div class="box">
          <div class="box-title">
            <h3><?php echo $this->__('Account Information') ?></h3>
          </div>
          <div class="box-content">
            <ul class="form-list unstyled">
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
                </li>
                <li>
                  <div class="kv">
                    <div class="key">
                      <?php echo $this->__('Email Address') ?><em>*</em>
                    </div>
                    <div class="value">
                      <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" class="input-text required-entry validate-email" />
                    </div>
                  </div>
                </li>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
            <?php endif ?>
                <li class="control" style="display:none;">
                  <label class="checkbox full-width">
                    <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Change Password')) ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox besides" />
                    <div class="cb-text">
                      <?php echo $this->__('Change Password') ?>
                    </div>
                  </label>
                </li>
            </ul>
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
          </div>
        </div>
    </div>
    <div class="columns small-12 medium-6" id="password-box">
      <div class="box">
        <div class="box-title">
          <h3><?php echo $this->__('Change Password') ?></h3>
        </div>
        <div class="box-content">
          <ul class="form-list unstyled">
              <li>
                <div class="kv">
                  <div class="key">
                    <?php echo $this->__('Current Password') ?><em>*</em>
                  </div>
                  <div class="value">
                    <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
                    <input type="text" class="input-text" name="dummy" id="dummy" style="display:none;"/>
                    <input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Current Password')) ?>" class="input-text" name="current_password" id="current_password" />
                  </div>
                </div>
              </li>
              <li class="fields">
                <div class="kv">
                  <div class="key">
                    <?php echo $this->__('New Password') ?><em>*</em>
                  </div>
                  <div class="value">
                    <input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('New Password')) ?>" class="input-text validate-password" name="password" id="password" />
                  </div>
                </div>
                <div class="kv">
                  <div class="key">
                    <?php echo $this->__('Confirm New Password') ?><em>*</em>
                  </div>
                  <div class="value">
                    <input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm New Password')) ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                  </div>
                </div>
              </li>
          </ul>
          <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        </div>
      </div>
    </div>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save')) ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('password-box').show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('password-box').hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }

    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>
