<div class="block block-login">
  <div class="block-title">
      <strong><span><?php echo $this->__('Login') ?></span></strong>
  </div>
  <form id="mini.login-form" action="<?php echo $this->getPostActionUrl() ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    <div class="block-content">
      <label for="mini-login"><?php echo $this->__('Email:') ?></label><input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" id="mini-login" class="input-text validate-email required-entry" />
      <label for="mini-password"><?php echo $this->__('Password:') ?></label><input type="password" name="login[password]" id="mini-password" class="input-text required-entry" />
      <?php /* <div class="input-block checkbox">
        <input type="checkbox" name="privacy_policy" value="1" title="<?php echo $this->__('Accept the privacy policy') ?>" class="checkbox required-entry">
        <label class="smaller">Ja, ich stimme den <a class="condition" href="<?php echo $this->getUrl('agb'); ?>" target="_blank">AGB</a> und den <a class="condition" href="<?php echo $this->getUrl('datenschutz'); ?>" target="_blank">Datenschutzbestimmungen</a> von Horsebrands zu.</label>
      </div> */ ?>
      <div class="actions">
        <button type="submit" class="button gold right"><span><span><?php echo $this->__('Login') ?></span></span></button>
        <a href="<?php echo $this->getUrl('customer/account/login') ?>" class="mini-registration-link">Noch kein Konto? Jetzt registrieren!</a>
      </div>
    </div>
  </form>
  <script type="text/javascript">
  //<![CDATA[
      var dataForm = new VarienForm('mini.login-form', true);
  //]]>
  </script>
</div>
