<div class="block block-login">
  <div class="block-title">
      <strong><span><?php echo $this->__('Login') ?></span></strong>
  </div>
  <form id="mini.login-form" action="<?php echo $this->getPostActionUrl() ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    <div class="block-content">
      <label for="mini-login"><?php echo $this->__('Email:') ?></label><input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" id="mini-login" class="input-text validate-email required-entry" />
      <label for="mini-password"><?php echo $this->__('Password:') ?></label><input type="password" name="login[password]" id="mini-password" class="input-text required-entry" />
      <a class="forgot-password right" href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>"><?php echo $this->__("Forgot Password") ?>?</a>
      <div class="actions">
        <button type="submit" class="button gold right"><span><span><?php echo $this->__('Log In') ?></span></span></button>
        <a href="<?php echo $this->getUrl('customer/account/login') ?>" class="mini-registration-link">Noch kein Konto? Jetzt registrieren!</a>
      </div>
    </div>
  </form>
  <script type="text/javascript">
  //<![CDATA[
      var dataForm = new VarienForm('mini.login-form', true);
  //]]>
  </script>
</div>
