<?php //$newsletterTypes = $this->getNewsletterTypes(); ?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
  <?php //echo 'nl types: ' . count($newsletterTypes); ?>
  <div class="fieldset">
      <?php echo $this->getBlockHtml('formkey')?>
      <label for="subscription">
        <!-- <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('General Subscription')) ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox besides" />
        <div class="cb-text">
          <strong><?php echo $this->__('General Subscription') ?></strong>
          <p>Beschreibung</p>
        </div> -->
        MOIN!
      </label>
          <?php /* Extensions placeholder */ ?>
          <?php echo $this->getChildHtml('customer.form.newsletter.extra')?>
      </ul>
  </div>
  <div class="buttons-set">
    <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save')) ?>" class="button right gold medium"><span><span><?php echo $this->__('Save') ?></span></span></button>
  </div>
  <?php foreach ($newsletterTypes as $newsletterType): ?>
    <?php echo $newsletterType->getTypeName() ?>
  <?php endforeach; ?>
</form>
<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('customer.form.newsletter.extra2')?>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
