<h2 class="title">Ich bin Neukunde <i class="fa fa-lock"></i></h2>
<div class="content clearfix">
  <form id="register-form" action="<?php echo $this->getPostActionUrl() ?>" method="post">
    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
    <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    <div class="input-container label-aside">
      <div class="input-block">
        <label>Vorname<em>*</em></label>
        <input type="text" class="input-text required-entry" name="firstname" />
      </div>
      <div class="input-block">
        <label>Nachname<em>*</em></label>
        <input type="text" class="input-text required-entry" name="lastname" />
      </div>
      <div class="input-block">
        <label>E-Mail-Adresse<em>*</em></label>
        <input type="text" class="input-text required-entry validate-email" name="email" />
      </div>
      <div class="input-block">
        <label>Passwort<em>*</em></label>
        <input type="password" class="full-width input-text required-entry" name="password" />
      </div>
      <div class="input-block">
        <label class="note">Passwort<em>*</em><span>(Wiederholen)</span></label>
        <input type="password" class="full-width input-text required-entry" name="confirmation" />
      </div>
      <div class="input-block checkbox">
        <div class="right-col">
          <input type="checkbox" name="privacy_policy" value="1" title="<?php echo $this->__('Accept the privacy policy') ?>" class="checkbox required-entry">
          <label class="smaller">Ja, ich stimme den <a class="condition" href="<?php echo $this->getUrl('agb'); ?>" target="_blank">AGB</a> und den <a class="condition" href="<?php echo $this->getUrl('datenschutz'); ?>" target="_blank">Datenschutzbestimmungen</a> von Horsebrands zu.</label>
        </div>
      </div>
      <div class="input-block checkbox">
        <div class="right-col">
          <input type="checkbox" name="is_subscribed" title="<?php echo $this->quoteEscape($this->__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed" class="checkbox" />
          <label class="smaller">Ja, ich m&ouml;chte &uuml;ber Trends, Aktionen, & Gutscheine per E-Mail informiert werden. Abmeldung jederzeit m&ouml;glich.</label>
        </div>
      </div>
      <div class="buttons-container" style="text-align: right;">
        <button type="submit" class="gold">Kostenlos registrieren</button>
        <div>
          <?php
          $block = $this->getLayout()->createBlock('inchoo_socialconnect/facebook_button')->setButtonText('Mit Facebook registrieren');
          echo $block->setTemplate('inchoo/socialconnect/facebook/button.phtml')->toHtml();
          ?>
        </div>
      </div>
    </div>
    <?php echo $this->getChildHtml('form.additional.info'); ?>
  </form>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('register-form', true);
    <?php if($this->getShowAddressFields()): ?>
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
    <?php endif; ?>
//]]>
</script>
