<div class="page-title">
  <h2><?php echo $this->__('Reset a Password'); ?></h2>
</div>
<?php echo $this->getMessagesBlock()->toHtml(); ?>
<form action="<?php echo $this->getUrl('*/*/resetpasswordpost'); ?>" method="post" id="form-validate" class="scaffold-form">
  <div class="forgotpassword-container">
    <div class="input-container label-aside">
      <div class="input-block">
        <label for="password" class="required"><?php echo $this->__('New Password'); ?><em>*</em></label>
        <input type="password" class="input-text required-entry validate-password" name="password" id="password" />
      </div>
      <div class="input-block">
        <label for="confirmation" class="required"><?php echo $this->__('Confirm New Password'); ?><em>*</em></label>
        <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
      </div>
      <?php echo $this->getChildHtml('form.additional.info'); ?>
      <p class="required"><?php echo $this->__('* Required Fields') ?></p>
      <div class="buttons-container clearfix">
        <button type="submit" class="gold right"><?php echo $this->__('Reset a Password'); ?></button>
      </div>
    </div>
  </div>
</form>
<script type="text/javascript">
/*<![CDATA[*/
    var dataForm = new VarienForm('form-validate', true);
/*]]>*/
</script>
