<h2 class="title"><?php echo $this->__('Shipping Address') ?></h2>
<div class="content">
<?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
  <?php $completeClass = $this->getCheckout()->getStepData('shipping', 'complete') ? 'complete' : ''; ?>
  <address><?php echo $this->getShipping()->format('html') ?></address>
  <a href="#changeShipping" onclick="checkout.changeSection('opc-billing'); return false;" class="progress-change">
    <i class="fa fa-pencil-square-o"></i>
  </a>
<?php else: ?>
  <p>
    <?php echo $this->__('No Shipping Address selected.') ?>
  </p>
<?php endif; ?>
</div>
