<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php $_isSaleableCategory = !($this->helper('horsebrands_rewrites')->isProductInCategory($_product, 114)); ?>

<?php if($_product->isSaleable() && $_isSaleableCategory): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped() && false): ?>
        <label for="qty"><?php echo $this->__('Qty:') ?></label>
        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty" />
        <?php endif; ?>

        <a class="btn expand btn-gold link-addtocart" id="product-addtocart-button" onclick="productAddToCartForm.submit(this)"><?php echo $buttonTitle ?></a>
        <!-- <button type="button" title="<?php echo $buttonTitle ?>" id="product-addtocart-button" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button> -->
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
