<?php
// Get Groupd Id and group name of user
$groupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
$groupName = Mage::getModel('customer/group')->load($groupId)->getCode();

$isDefaultSubscribed = Mage::getModel('crconnect/newsletter_subscriber')->isSubscribed();
$isCustomSubscribed = Mage::getModel('crconnect/newsletter_subscriber')->isSubscribed($groupId);
?>
<div class="row">
    <div class="columns small-12 medium-6">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Contact Information') ?></h3>
                <a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a>
            </div>
            <div class="box-content">
                <p>
                    <?php echo $this->escapeHtml($this->getCustomer()->getName()) ?><br />
                    <?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?><br />
                    <a href="<?php echo $this->getChangePasswordUrl() ?>" style="display:none;"><?php echo $this->__('Change Password') ?></a>
                </p>
            </div>
        </div>
    </div>
    <?php if( $this->isNewsletterEnabled() ): ?>
    <div class="columns small-12 medium-6">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Newsletters') ?></h3>
                <a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit') ?></a>
            </div>
            <div class="box-content">
                <p>
                    <?php if( $isDefaultSubscribed ): ?>
                        <?php echo Mage::helper('crconnect')->__("You are currently subscribed to 'General Subscription'") ?><br>
                    <?php endif; ?>
                    <?php if( $isCustomSubscribed && $groupId > 1): ?>
                        <?php echo Mage::helper('crconnect')->__("You are currently subscribed to '%s Subscription'", $groupName) ?><br>
                    <?php endif; ?>
                    <?php if( !$isDefaultSubscribed && !$isCustomSubscribed ): ?>
                        <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
                    <?php endif; ?>
                </p>
            </div>
        </div>
    </div>
    <?php endif; ?>
</div>
