<div class="dashboard-sales-history">
    <div class="row">
      <div class="columns small-12">
        <div class="box">
          <h2 class="title">Letzte Bestellungen<span class="edit"><a href="<?php echo $this->getUrl('sales/order/history') ?>">Alle ansehen</a></span></h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="columns small-12">
        <div class="box">
          <h2 class="title">Tabelle</h2>
          <div class="content">
            <p>
              Zeige letzte 3 Bestellungen
            </p>
          </div>
        </div>
      </div>
    </div>
</div>
