<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_category = (mage::registry('current_category') ? mage::registry('current_category') : null);

    $_toolbar = $this->getToolbarBlock();
?>
<div class="category-products">
  <?php if($_category): ?>
    <h3><?php echo $_category->getName(); ?> <span class="products-count">/ <?php echo $_toolbar->getTotalNum() ?></span></h3>
  <?php endif; ?>

<?php echo $this->getChildHtml('catalog.filter') ?>

<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php //echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
      <?php // no no list mode... - list mode not here ?>
    <?php else: ?>
    <?php // Grid Mode ?>

    <?php $gridSize = 3; ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
      <?php $i++ ?>
      <!-- if($_item->getProduct()->getData('manufacturer')) { $manufacturer = $_item->getProduct()->getAttributeText('manufacturer'); } -->
      <?php $manufacturer = $_product->getAttributeText('manufacturer'); ?>

      <?php $firstInRow = ($i % $gridSize == 1) ?>
      <?php $lastInRow = ($i % $gridSize == 0) ?>
      <?php $lastInCollection = ($i == $_collectionSize) ?>

      <?php // new row? ?>
      <?php if($firstInRow): ?>
        <div class="row full-width smaller-margins products-row">
      <?php endif ?>
          <div class="columns medium-4<?php echo ($lastInCollection ? ' end' : ''); ?>">
            <div class="productlist-element item <?php echo $_product->getTypeId() ?>">
              <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php $_imgSize = 210; ?>
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                   src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(480,510); ?>" width="100%" height="255"
                   alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
               <div class="product-info">
                 <div class="top-row">
                   <div class="product-manufacturer"><?php echo ($manufacturer != '' ? $manufacturer : '&nbsp;'); ?></div>
                   <div class="product-price"><?php echo Mage::helper('core')->currency($_product->getFinalPrice(),true,false); ?></div>
                   <?php /* $_msrp = $_helper->productAttribute($_product, $_product->getMsrp(), 'msrp') ?>
                   <?php $_msrpPrice = $this->helper('core')->currency($_msrp,true,true) ?>
                   <?php if($_msrp): ?>
                     <span class="msrp"><?php echo $_msrpPrice; ?></span>
                   <?php endif; */ ?>
                 </div>
                 <div class="bottom-row">
                   <div class="product-name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></div>
                 </div>
               </div>
              </a>
              <?php
              // Provides extra blocks on which to hang some features for products in the list
              // Features providing UI elements targeting this block will display directly below the product name
              if ($this->getChild('name.after')) {
                  $_nameAfterChildName = 'product_list.swatches';
                  if ($_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName)) {
                    echo '<div class="offcanvas offcanvas-left">';
                    $_nameAfterChild->setProduct($_product);
                    echo $_nameAfterChild->toHtml();
                    echo '</div>';
                  }
              }
              ?>
              <div class="offcanvas offcanvas-bottom">
                foundation badges <?php echo 'saleable: ' . ($_product->isSaleable() ? 'true' : 'false') ?>
                <?php
                // Provides extra blocks on which to hang some features for products in the list
                // Features providing UI elements targeting this block will display directly below the product name
                if (false && $this->getChild('name.after')) {
                    $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                    foreach ($_nameAfterChildren as $_nameAfterChildName) {
                        $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                        $_nameAfterChild->setProduct($_product);
                        echo $_nameAfterChild->toHtml();
                    }
                }
                ?>
              </div>
              <!-- </a> -->
            </div>
          </div>

            <?php /* <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(232,245); ?>" width="232" height="245" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </li> --> */ ?>

        <?php // close row? ?>
        <?php if ($lastInRow || $lastInCollection): ?>
          </div>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
<?php endif; ?>
</div>

<script>
  // jQuery(document).ready(function($) {
  //   var parent = $('div.offcanvas.offcanvas-left').parent('.productlist-element');
  //   var element = $('div.offcanvas.offcanvas-left');
  //
  //   element.height(parent.height() - 2);
  // });
  $j(window).load(function() {
    var parent = $j('div.offcanvas.offcanvas-left').parent('.productlist-element');
    var element = $j('div.offcanvas.offcanvas-left');

    element.height(parent.height() - 2);
  });
</script>
