<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php $storeId = Mage::app()->getStore()->getStoreId(); ?>
<?php $manufacturerSwatchesBaseUrl = mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/swatches/manufacturer/'; ?>
<?php $summaryData = Mage::getModel('review/review_summary')->setStoreId($storeId)->load($_product->getId()); ?>

<script type="text/javascript">
  //<![CDATA[
  var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
  //]]>
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view">
  <div class="product-essential">
    <div class="product-essential-left">
      <!-- images -->
      <div class="image-gallery-wrapper">
        <?php echo $this->getChildHtml('media') ?>
      </div>
    </div>
    <div class="product-essential-right">
      <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <?php echo $this->getBlockHtml('formkey') ?>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
        <!-- product info -->
        <div class="row">
          <div class="manufacturer-logo left">
            <?php $manufacturerName = $_product->getAttributeText('manufacturer'); ?>
            <?php $manufacturerId = $_product->getManufacturer(); ?>
            <?php $manufacturer = Mage::getModel('Purchase/supplier')->load($manufacturerId, 'sup_code'); ?>
            <?php $imgUrl = $manufacturer->getsup_logo(); ?>
            <?php if($imgUrl): ?>
              <?php $imgUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .DS. 'manufacturer' .DS. 'logos' .DS. $imgUrl; ?>
              <img src="<?php echo $imgUrl ?>" alt="<?php echo $manufacturerName ?>" class="img-responsive" />
            <?php else: ?>
              <?php echo $manufacturerName ?>
            <?php endif; ?>
          </div>
          <div class="review-stars right" style="text-align:right;">
            <p class="rating overall-rating">
              <?php $numStarsTotal = intval($summaryData->getRatingSummary()/20);
              for ($i=1; $i <= 5 ; $i++) {
                echo '<i class="fa fa-star' . ($i>$numStarsTotal ? '-o' : '') . '"></i>';
              }
              ?>
            </p>
          </div>
        </div>
        <div class="row">
          <div class="columns medium-12 product-name">
            <h1 class="thin-weight"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
          </div>
        </div>
        <div class="row">
          <div class="columns medium-12">
              <div class="price-info">
                  <?php echo $this->getPriceHtml($_product); ?>
                  <?php echo $this->getChildHtml('bundle_prices') ?>
                  <?php echo $this->getTierPriceHtml() ?>
                  <span class="note">
                  <?php echo
                    (Mage::helper('tax')->priceIncludesTax() ?
                      $this->__('incl. VAT, %sexcl. shipping%s','<a class="text-underline" href="'.$this->getUrl('faq#lieferungversand').'">','</a>')
                      : $this->__('excl. VAT and %sshipping%s','<a class="text-underline" href="'.$this->getUrl('faq#lieferungversand').'">','</a>')); ?>
                  </span>
              </div>
          </div>
        </div>
        <div class="row">
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php elseif (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php elseif (!$_product->isSaleable()): ?>
                <div class="add-to-box">
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
            <?php endif; ?>
        </div>

        <?php if($_product->isSaleable() && Mage::getResourceModel('catalog/product')->getAttributeRawValue($_product->getId(), 'delivery_time', $storeId)): ?>
        <div class="row">
          <div class="columns medium-12">
            <?php $deliveryAttributes = array('delivery_time') ?>
            <ul class="unstyled check-items delivery-time-wrapper">
              <?php foreach ($deliveryAttributes as $att_code): ?>
                <?php if(Mage::getResourceModel('catalog/product')->getAttributeRawValue($_product->getId(), $att_code, $storeId)): ?>
                <li>
                  <?php if($att_code == 'delivery_time'): ?>
                    <?php echo $this->__('Delivery during').' ' ?>
                  <?php endif; ?>
                  <?php echo $_product->getAttributeText($att_code); ?>
                </li>
                <?php endif; ?>
              <?php endforeach; ?>
            </ul>
          </div>
        </div>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
        <div class="row">
          <div class="columns medium-12">
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
          </div>
        </div>
        <?php endif;?>

        <div class="row">
          <div class="columns medium-12">
            <ul class="unstyled">
              <li class="promotion-element expand return-icon">14 Tage R&uuml;ckgaberecht</li>
              <li class="promotion-element expand phone-icon">Hotline <?php echo Mage::getStoreConfig('general/store_information/phone') ?></li>
              <?php /* <li class="promotion-element expand delivery-icon">Versandkostenfrei</li> */ ?>
            </ul>
          </div>
        </div>
      </form>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    <div class="product-essential-left">
      <div class="description-wrapper">
        <?php echo $this->getChildHtml('description') ?>
      </div>
    </div>
  </div>

  <?php echo $this->getChildHtml('upsell_products') ?>

  <div class="row smaller-margins full-width customerratings-container">
    <div class="columns medium-12">
      <section>
        <h5 class="section-title"><?php echo $this->__('Customer Reviews'); ?></h5>
        <div>
          <?php echo $this->getChildHtml('product_review'); ?>
        </div>
      </section>
    </div>
  </div>
</div>
