<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php $storeId = Mage::app()->getStore()->getStoreId(); ?>
<?php $manufacturerSwatchesBaseUrl = mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/swatches/manufacturer/'; ?>
<?php $summaryData = Mage::getModel('review/review_summary')->setStoreId($storeId)->load($_product->getId()); ?>


<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view">
    <div class="row smaller-margins full-width product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <?php echo $this->getBlockHtml('formkey') ?>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="columns medium-8 product-essential-left">
          <!-- img and description -->
          <div class="row full-width">
            <?php echo $this->getChildHtml('media') ?>
          </div>
          <div class="row full-width description-wrapper">
            <?php echo $this->getChildHtml('description') ?>
          </div>
        </div>
        <div class="columns medium-4 product-essential-right">
          <!-- product info -->
          <div class="row">
            <div class="manufacturer-logo left">
              <?php $manufacturerName = $_product->getAttributeText('manufacturer'); ?>
              <?php $manufacturerId = $_product->getManufacturer(); ?>
              <?php $manufacturer = Mage::getModel('Purchase/supplier')->load($manufacturerId, 'sup_code'); ?>
              <?php $imgUrl = $manufacturer->getsup_logo(); ?>
              <?php if($imgUrl): ?>
                <?php $imgUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .DS. 'manufacturer' .DS. 'logos' .DS. $imgUrl; ?>
                <img src="<?php echo $imgUrl ?>" alt="<?php echo $manufacturerName ?>" class="img-responsive" />
              <?php else: ?>
                <?php echo $manufacturerName ?>
              <?php endif; ?>
            </div>
            <div class="review-stars right" style="text-align:right;">
              <p class="rating overall-rating">
                <?php $numStarsTotal = intval($summaryData->getRatingSummary()/20);
                for ($i=1; $i <= 5 ; $i++) {
                  echo '<i class="fa fa-star' . ($i>$numStarsTotal ? '-o' : '') . '"></i>';
                }
                ?>
              </p>
            </div>
          </div>
          <div class="row">
            <div class="columns medium-12 product-name">
              <h1 class="thin-weight"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>
          </div>
          <div class="row">
            <div class="columns medium-12">
              <h1 class="normal-weight">
                <?php echo Mage::helper('core')->currency($_product->getFinalPrice(),true,false); ?>
                <span class="note">
                  <?php echo (Mage::helper('tax')->priceIncludesTax() ? 'inkl. MwSt' : 'exkl. MwSt'); ?>
                </span>
              </h1>
            </div>
          </div>
          <div class="row no-margin">
              <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                  <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
              <?php endif;?>
          </div>
          <?php if(Mage::getResourceModel('catalog/product')->getAttributeRawValue($_product->getId(), 'delivery_time', $storeId)): ?>
          <div class="row">
            <div class="columns medium-12">
              <?php $deliveryAttributes = array('delivery_time') ?>
              <ul class="unstyled check-items delivery-time-wrapper">
                <?php foreach ($deliveryAttributes as $att_code): ?>
                  <?php if(Mage::getResourceModel('catalog/product')->getAttributeRawValue($_product->getId(), $att_code, $storeId)): ?>
                  <li>
                    <?php if($att_code == 'delivery_time'): ?>
                      Lieferbar innerhalb von
                    <?php endif; ?>
                    <?php echo $_product->getAttributeText($att_code); ?>
                  </li>
                  <?php endif; ?>
                <?php endforeach; ?>
              </ul>
            </div>
          </div>
          <?php endif; ?>

          <?php if ($_product->isSaleable() && $this->hasOptions()):?>
          <div class="row double-margin">
            <div class="columns medium-12">
                  <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            </div>
          </div>
          <?php endif;?>

          <div class="row">
            <div class="columns medium-12">
              <ul class="unstyled">
                <li class="promotion-element expand return-icon">14 Tage R&uuml;ckgaberecht</li>
                <li class="promotion-element expand phone-icon">Hotline 0251/67448555</li>
                <li class="promotion-element expand delivery-icon">Versandkostenfrei</li>
              </ul>
            </div>
          </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>
    <div class="row smaller-margins full-width crossselling-container">
      <div class="columns medium-12">
        <section>
          <h5 class="section-title">&Auml;hnliche Produkte</h5>
          <div>
            Produkte Slider
          </div>
        </section>
      </div>
    </div>

    <div class="row smaller-margins full-width customerratings-container">
      <div class="columns medium-12">
        <section>
          <h5 class="section-title">&nbsp;</h5>
          <div>
            <?php echo $this->getChildHtml('product_review'); ?>
          </div>
        </section>
      </div>
    </div>

    <?php /* ?>
    <div class="product-collateral">
<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <div class="box-collateral <?php echo "box-{$alias}"?>">
            <?php if ($title = $this->getChildData($alias, 'title')):?>
            <h2><?php echo $this->escapeHtml($title); ?></h2>
            <?php endif;?>
            <?php echo $html; ?>
        </div>
<?php endforeach;?>
        <?php echo $this->getChildHtml('upsell_products') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
    </div>
    <?php */ ?>

</div>
