<?php
    $_order  = $this->getOrder();
    $_source = $this->getSource();
    $_fullInfo = $_order->getFullTaxInfo();
    $_weees = $this->helper('tax')->getAllWeee($_order);
    global $taxIter; $taxIter++;
    $hasItemsInTaxSection = 0;
?>

<?php // Horsebrands: Hide Tax - show in invoice only: tax.order.print.phtml  ?>
<tr class="tax" style="display: none;">
  <td style="padding: 2px 0; padding-right: 40px; text-align: right;">
    <?php echo $this->__('Tax'); ?>:
  </td>
  <td style="padding: 2px 0; text-align: right;">
    <span class="totals-price"><?php echo $_order->formatPrice($_source->getTaxAmount()) ?></span>
  </td>
</tr>
