<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form id="checkout_multishipping_form" action="<?php echo $this->getPostActionUrl() ?>" method="post">
  <div class="row full-width small-margins">
    <div class="columns small-12 medium-6">
      <div class="box" id="billingcontent">
        <h2 class="title"><?php echo $this->__('Billing Address'); ?></h2>
        <div class="content clearfix">
            <input type="hidden" name="billing[address_id]" value="<?php echo $this->getBillingAddress()->getId() ?>" id="billing:address_id" />
            <div class="customer-address">
              <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getBillingAddress()->getFirstname() ? $this->getBillingAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!Mage::getSingleton('customer/session')->isLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
              <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('Street'); ?><em>*</em></label>
                </div>
                <div class="value">
                  <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                  <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getBillingAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                  <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                  <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getBillingAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                  <?php endfor; ?>
                </div>
              </div>
              <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('c/o'); ?></label>
                </div>
                <div class="value">
                  <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->escapeHtml($this->getBillingAddress()->getCompany()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" onchange="shipping.setSameAsBilling(false);" />
                </div>
              </div>
              <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('Post Code'); ?><em>*</em></label>
                </div>
                <div class="value">
                  <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getBillingAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                </div>
              </div>
              <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('City'); ?><em>*</em></label>
                </div>
                <div class="value">
                  <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getBillingAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="billing:city" />
                </div>
              </div>
              <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('Country'); ?><em>*</em></label>
                </div>
                <div class="value">
                  <?php echo $this->getCountryHtmlSelect('billing') ?>
                </div>
              </div>
              <?php if(false): //guest checkout ?>
              <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('E-Mail-Address'); ?><em>*</em></label>
                </div>
                <div class="value">
                  <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getBillingAddress()->getEmail()) ?>" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" class="input-text validate-email required-entry" />
                </div>
              </div>
              <?php endif; //guest checkout ?>
              <div class="kv">
                <div class="key">
                  <label for="billing:telephone"><?php echo $this->__('Telephone') ?><em>*</em></label>
                </div>
                <div class="value">
                  <input type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getBillingAddress()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?> required-entry" id="billing:telephone" />
                </div>
              </div>
              <input type="hidden" name="billing[save_in_address_book]" value="1" />
              <div class="same-as-billing-container">
                <input type="checkbox" id="billing:use_for_shipping" value="0" title="<?php echo $this->__('Ship to different address') ?>" />
                <label for="billing:use_for_shipping"><?php echo $this->__('Ship to different address') ?></label>
                <div style="display: none !important;">
                  <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" checked="checked" title="<?php echo  Mage::helper('core')->quoteEscape($this->__('Ship to this address')) ?>" onclick="$('shipping:same_as_billing').checked = true;" class="radio" /><label for="billing:use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label>
                  <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Ship to different address')) ?>" onclick="$('shipping:same_as_billing').checked = false;" class="radio" /><label for="billing:use_for_shipping_no"><?php echo $this->__('Ship to different address') ?></label>
                </div>
              </div>
        </div>
      </div>
    </div>
  </div>
  <div class="columns small-12 medium-6">
    <div class="box">
      <h2 class="title"><?php echo $this->__('Shipping Address'); ?></h2>
      <div class="content clearfix">
        <p id="same-as-billing-text">
          <?php echo $this->__('Same as Billing Address'); ?>
        </p>
        <div id="shippingcontent" style="display: none;">
          <div id="shipping-address-form" class="scaffold-form">
            <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getShippingAddress()->getId() ?>" id="shipping:address_id" />
            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getShippingAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>
            <div class="kv">
              <div class="key">
                <label><?php echo $this->__('c/o'); ?></label>
              </div>
              <div class="value">
                <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getShippingAddress()->getCompany()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" onchange="shipping.setSameAsBilling(false);" />
              </div>
            </div>
            <div class="kv">
              <div class="key">
                <label><?php echo $this->__('Street'); ?><em>*</em></label>
              </div>
              <div class="value">
                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getShippingAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                  <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getShippingAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                <?php endfor; ?>
              </div>
            </div>
            <div class="kv">
              <div class="key">
                <label><?php echo $this->__('Post Code'); ?><em>*</em></label>
              </div>
              <div class="value">
                <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getShippingAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onchange="shipping.setSameAsBilling(false);" />
              </div>
            </div>
            <div class="kv">
              <div class="key">
                <label><?php echo $this->__('City'); ?><em>*</em></label>
              </div>
              <div class="value">
                <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getShippingAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
              </div>
            </div>
            <div class="kv">
              <div class="key">
                <label><?php echo $this->__('Country'); ?><em>*</em></label>
              </div>
              <div class="value">
                <?php echo $this->getCountryHtmlSelect('shipping') ?>
              </div>
            </div>
            <div class="kv">
              <div class="key">
                <label for="shipping:telephone"><?php echo $this->__('Telephone') ?><em>*</em></label>
              </div>
              <div class="value">
                <input type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getShippingAddress()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" />
              </div>
            </div>
            <input type="hidden" name="shipping[save_in_address_book]" value="1" />
            <input type="hidden" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1" />
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="buttons-set" id="billing-buttons-container">
    <div id="shipping-buttons-container">
      <button class="opc-back-button white left" onclick="checkout.back(); return false;"><?php echo $this->__('Back'); ?></button>
      <button class="opc-next-button gold right" id="btnBillingContinue" type='submit' style="font-weight: 900;text-transform: uppercase;letter-spacing: .05em;"><?php echo $this->__('Continue'); ?></button>
      <span class="please-wait" id="billing-please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
      </span>
      <span class="please-wait" id="shipping-please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
      </span>
    </div>
  </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var form = new VarienForm('checkout_multishipping_form', true);
    // var shipping = new Shipping('co-address-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveAddress') ?>');
    // var shippingForm = new VarienForm('co-address-form');
    //
    // $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);
    // $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    jQuery(document).ready(function ($j) {
        if($j('#shippingcontent').find('input').hasClass('validation-failed')) {
            $j('input:checkbox[name="billing[use_for_shipping]"]').prop('checked');
            $j('#shippingcontent').show(100);
        }
        $j('#billing\\:use_for_shipping').change(function () {
            $j('#shippingcontent').toggle(100);
            $j('#same-as-billing-text').toggle(100);

            var $element = $j("#shipping\\:same_as_billing");
            if($element.val() == 0) {
              $element.val('1');
              $j('#billing\\:use_for_shipping_no').prop('checked',false);
              $j('#billing\\:use_for_shipping_yes').prop('checked',true);
            } else {
              $element.val('0');
              $j('#billing\\:use_for_shipping_yes').prop('checked',false);
              $j('#billing\\:use_for_shipping_no').prop('checked',true);
            }
        });
    });
//]]>
</script>
