<?php
    $_methods       = $this->getMethods();
    $_methodsCount  = count($_methods);
?>

<div class="multiple-checkout">
  <?php echo $this->getMessagesBlock()->toHtml() ?>
  <script src="<?php echo Mage::getBaseUrl('js') ?>varien/payment.js" type="text/javascript"></script>
  <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="multishipping-billing-form">
    <?php echo $this->getChildHtml('payment_methods_before') ?>
    <div class="fieldset">
      <?php foreach ($_methods as $_method): $_code = $_method->getCode() ?>
        <div id="dt_method_<?php echo $_code ?>" class="checkout-payment-method-wrapper">
          <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->escapeHtml($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
          <label for="p_method_<?php echo $_code ?>" class="method-title"><?php echo $this->escapeHtml($_method->getTitle()) ?></label>
          <span class="icon-paymentmethod"><img src="<?php echo $this->getSkinUrl('images/icons/payment/icon-'.$_code.'.svg') ?>" alt="<?php echo $_code ?>" /></span>
          <?php if ($html = $this->getChildHtml('payment.method.'.$_code)): ?>
            <div id="dd_method_<?php echo $_code ?>" class="payment-method-input-wrapper">
              <?php echo $html; ?>
            </div>
          <?php endif; ?>
        </div>
      <?php endforeach; ?>
      <?php echo $this->getChildHtml('payment_methods_after') ?>
    </div>
    <div class="tool-tip" id="payment-tool-tip" style="display:none;">
        <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close')) ?>"><?php echo $this->__('Close') ?></a></div>
        <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Card Verification Number Visual Reference')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Card Verification Number Visual Reference')) ?>" /></div>
    </div>
    <div class="buttons-set">
      <button class="opc-back-button white left" onclick="window.location='<?php echo $this->getBackUrl() ?>'; return false;"><?php echo $this->__('Back'); ?></button>
      <button class="opc-next-button gold right" type='submit'><?php echo $this->__('Continue'); ?></button>
    </div>
  </form>
  <script type="text/javascript">
  //<![CDATA[
      var payment = new paymentForm('multishipping-billing-form');
      var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
      function toggleToolTip(event){
          if($('payment-tool-tip')){
              /*$('payment-tool-tip').setStyle({
                  top: (Event.pointerY(event)-510)+'px',
                  left: (Event.pointerX(event)-800)+'px'
              })*/
              $('payment-tool-tip').toggle();
          }
          Event.stop(event);
      }
      if($('payment-tool-tip-close')){
          Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
      }
      $$('.cvv-what-is-this').each(function(element){
          Event.observe(element, 'click', toggleToolTip);
      });
  //]]>
  </script>
</div>
