<?php /** @var $this Mage_Checkout_Block_Multishipping_Overview */ ?>
<div class="multiple-checkout review-container clearfix">
  <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
  <form id="review-order-form" action="<?php echo $this->getPostActionUrl() ?>" method="post" onsubmit="return showLoader();">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div class="order-review">
      <div class="title-container">
        <h2><?php echo $this->__('Your Order') ?></h2>
      </div>
      <?php foreach ($this->getShippingAddresses() as $_index => $_address): ?>
        <div class="overview-items">
          <div class="item-table-title">
            <h2><?php echo $_index+1 . '. ' . $this->__('Delivery') ?></h2>
          </div>
          <table class="data-table">
            <col width="30%" />
            <col width="70%" />
            <thead>
              <th>&nbsp;</th>
              <th>&nbsp;</th>
            </thead>
            <tbody>
              <?php foreach ($this->getShippingAddressItems($_address) as $_item): ?>
                <?php echo $this->getRowItemHtml($_item); ?>
              <?php endforeach; ?>
            </tbody>
            <tfoot class="multi-totals">
              <?php echo $this->renderTotals($this->getShippingAddressTotals($_address)); ?>
            </tfoot>
          </table>
        </div> <!-- .end overview-items-xx -->
      <?php endforeach; ?>
      <?php echo $this->getChildHtml('items_after'); ?>
      <div class="grandtotal-wrapper clearfix">
        <?php echo $this->getChildHtml('agreements') ?>
        <div class="text-right totals">
          <strong>
            <?php echo $this->__('Grand Total to pay:') ?>
            <span class="totals-price"><span class="price"><?php echo $this->helper('checkout')->formatPrice($this->getTotal()) ?></span></span>
          </strong>
        </div>
      </div>
      <div id="review-buttons-container" class="buttons-set">
          <button type="submit" title="<?php echo $this->quoteEscape($this->__('Place Order')) ?>" class="button btn-checkout" id="review-button"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
      </div>
    </div>
    <div id="checkout-progress-wrapper" class="opc-sidebar-block opc-progress-container">
      <!-- billing address -->
      <div class="box">
        <h2 class="title"><?php echo $this->__('Billing Address') ?></h2>
        <div class="content">
          <?php $_address=$this->getBillingAddress() ?>
          <address><?php echo $_address->format('html') ?></address>
          <a href="<?php echo $this->getEditShippingAddressUrl($_address) ?>" class="progress-change">
            <i class="fa fa-pencil-square-o"></i>
          </a>
        </div>
      </div>
      <!-- shipping address -->
      <div class="box">
        <h2 class="title"><?php echo $this->__('Shipping Address') ?></h2>
        <div class="content">
          <?php $_address = $this->getShippingAddresses()[0]; ?>
          <address><?php echo $_address->format('html') ?></address>
          <a href="<?php echo $this->getEditShippingAddressUrl($_address) ?>" class="progress-change">
            <i class="fa fa-pencil-square-o"></i>
          </a>
        </div>
      </div>
      <!-- shipping methods -->
      <div class="box">
        <h2 class="title"><?php echo $this->__('Shipping Method') ?></h2>
        <div class="content">
          <dl>
          <?php foreach ($this->getShippingAddresses() as $_index => $_address): ?>
            <?php if($_rate=$this->getShippingAddressRate($_address)): ?>
            <dt>
              <?php echo $_index+1 . '. ' . $this->__('Delivery ') ?>
            </dt>
            <dd>
              <?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
              <?php echo $this->getShippingPriceExclTax($_address); ?>
            </dd>
            <?php endif; ?>
          <?php endforeach; ?>
          </dl>
        </div>
      </div>
      <!-- payment method -->
      <div class="box">
        <h2 class="title"><?php echo $this->__('Payment Method') ?></h2>
        <div class="content">
          <input type="hidden" name="payment[cc_number]" value="<?php echo $this->escapeHtml($this->getPayment()->getCcNumber())?>" />
          <input type="hidden" name="payment[cc_cid]" value="<?php echo $this->escapeHtml($this->getPayment()->getCcCid())?>" />
          <?php echo $this->getPaymentHtml() ?>
          <a href="<?php echo $this->getEditBillingUrl() ?>" class="progress-change">
            <i class="fa fa-pencil-square-o"></i>
          </a>
        </div>
      </div>
      <div class="box">
        <h2 class="title">&nbsp;</h2>
        <div class="content">
          <?php echo Mage::getBlockSingleton('cms/block')->setBlockId('review_agreement_process')->toHtml(); ?>
        </div>
      </div>
    </div>
  </form>
  <script type="text/javascript">
  //<![CDATA[
      var submitted = false;

      function showLoader()
      {
          if (submitted) {
              return false;
          }
          if ($('checkout-agreements')) {
              var checkboxes = $$('#checkout-agreements input');
              for (var i=0, l=checkboxes.length; i<l; i++) {
                  if (!checkboxes[i].checked) {
                      alert("<?php echo $this->jsQuoteEscape($this->__('Please agree to all Terms and Conditions before placing the orders.')) ?>");
                      return false;
                  }
              }
          }

          submitted = true;
          var step='review';
          Element.show(step+'-please-wait');
          $(step+'-buttons-container').setStyle({opacity:.5});
          $(step+'-buttons-container').descendants().each(function(s) {
                s.disabled = true;
          });
          return true;
      }
  //]]>
  </script>
</div>
