<?php $_creditmemo = $this->getCreditmemo() ?>
<?php $_order      = $this->getOrder() ?>

<?php if ($_creditmemo && $_order): ?>
  <?php $_items      = $_order->getAllItems() ?>
  <?php $_itemCount  = count($_items) ?>
  <tr>
    <td class="inner contents">
      <table class="items" cellpadding="0" cellspacing="0" border="0">
        <thead>
          <tr>
            <th class="cell-name"><?php echo $this->__('Items'); ?></th>
            <th class="cell-name align-center"><?php echo $this->__('Qty'); ?></th>
            <th class="cell-name align-right"><?php echo $this->__('Price'); ?></th>
          </tr>
        </thead>
        <?php $i=0; foreach ($_creditmemo->getAllItems() as $_item): ?>
          <?php if($_item->getOrderItem()->getParentItem()) continue; else $i++; ?>
          <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach; ?>
        <tfoot>
          <?php echo $this->getChildHtml('creditmemo_totals');?>
        </tfoot>
      </table>
    </td>
  </tr>
<?php endif; ?>
