<div class="<?php echo $this->getContainerClassName()?>">
<?php if ($this->showPrefix()): ?>
  <div class="kv">
    <div class="key">
      <label><?php echo $this->getStoreLabel('prefix') ?><?php if ($this->isPrefixRequired()) echo '<em>*</em>' ?></label>
    </div>
    <div class="value">
      <?php if ($this->getPrefixOptions() === false): ?>
          <input type="text" id="<?php echo $this->getFieldId('prefix')?>" name="<?php echo $this->getFieldName('prefix')?>" value="<?php echo $this->escapeHtml($this->getObject()->getPrefix()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->getStoreLabel('prefix')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('prefix') ?>" <?php echo $this->getFieldParams() ?> />
      <?php else: ?>
        <select id="<?php echo $this->getFieldId('prefix')?>" name="<?php echo $this->getFieldName('prefix')?>" title="<?php echo Mage::helper('core')->quoteEscape($this->getStoreLabel('prefix')) ?>" class="<?php echo $this->helper('customer/address')->getAttributeValidationClass('prefix') ?>" <?php echo $this->getFieldParams() ?>>
        <?php foreach ($this->getPrefixOptions() as $_option): ?>
            <option value="<?php echo $_option?>"<?php if ($this->getObject()->getPrefix()==$_option):?> selected="selected"<?php endif; ?>><?php echo $this->__($_option)?></option>
        <?php endforeach; ?>
        </select>
      <?php endif; ?>
    </div>
  </div>
<?php endif; ?>

<div class="kv">
  <div class="key">
    <label><?php echo $this->getStoreLabel('firstname') ?><em>*</em></label>
  </div>
  <div class="value">
    <input type="text" id="<?php echo $this->getFieldId('firstname')?>" name="<?php echo $this->getFieldName('firstname')?>" value="<?php echo $this->escapeHtml($this->getObject()->getFirstname()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->getStoreLabel('firstname')) ?>" maxlength="255" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('firstname') ?>" <?php echo $this->getFieldParams() ?> />
  </div>
</div>

<?php if ($this->showMiddlename()): ?>
<?php $isMiddlenameRequired = $this->isMiddlenameRequired(); ?>
  <div class="kv">
    <div class="key">
      <label><?php echo $this->getStoreLabel('middlename') ?><?php echo $isMiddlenameRequired ? '<em>*</em>' : '' ?></label>
    </div>
    <div class="value">
      <input type="text" id="<?php echo $this->getFieldId('middlename')?>" name="<?php echo $this->getFieldName('middlename')?>" value="<?php echo $this->escapeHtml($this->getObject()->getMiddlename()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->getStoreLabel('middlename')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('middlename') ?>" <?php echo $this->getFieldParams() ?> />
    </div>
  </div>
<?php endif; ?>

<div class="kv">
  <div class="key">
    <label><?php echo $this->getStoreLabel('lastname') ?><em>*</em></label>
  </div>
  <div class="value">
    <input type="text" id="<?php echo $this->getFieldId('lastname')?>" name="<?php echo $this->getFieldName('lastname')?>" value="<?php echo $this->escapeHtml($this->getObject()->getLastname()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->getStoreLabel('lastname')) ?>" maxlength="255" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('lastname') ?>" <?php echo $this->getFieldParams() ?> />
  </div>
</div>

<?php if ($this->showSuffix()): ?>
<div class="kv">
  <div class="key">
    <label><?php echo $this->getStoreLabel('suffix') ?><?php if ($this->isSuffixRequired()) echo '<em>*</em>' ?></label>
  </div>
  <div class="value">
    <?php if ($this->getSuffixOptions() === false): ?>
        <input type="text" id="<?php echo $this->getFieldId('suffix')?>" name="<?php echo $this->getFieldName('suffix')?>" value="<?php echo $this->escapeHtml($this->getObject()->getSuffix()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->getStoreLabel('suffix')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('suffix') ?>" <?php echo $this->getFieldParams() ?> />
    <?php else: ?>
        <select id="<?php echo $this->getFieldId('suffix')?>" name="<?php echo $this->getFieldName('suffix')?>" title="<?php echo Mage::helper('core')->quoteEscape($this->getStoreLabel('suffix')) ?>" class="<?php echo $this->helper('customer/address')->getAttributeValidationClass('suffix') ?>" <?php echo $this->getFieldParams() ?>>
        <?php foreach ($this->getSuffixOptions() as $_option): ?>
            <option value="<?php echo $_option?>"<?php if ($this->getObject()->getSuffix()==$_option):?> selected="selected"<?php endif; ?>><?php echo $this->__($_option)?></option>
        <?php endforeach; ?>
        </select>
    <?php endif; ?>
  </div>
</div>
<?php endif; ?>
</div>
