<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
  <h1><?php echo $this->__('My Orders') ?></h1>
</div>
<ul class="messages">
  <li class="success-msg" style="display: none; color:#1d1d1d; border-color: #cca64b">
    <ul>
      <li>
        <span>
          Du möchtest einen Artikel zurücksenden, aber findest deine Bestellung nicht?<br />
          Durch das Aufsetzen des neuen Systems kann es vereinzelt dazu kommen, dass Kunden ihre vorherigen Bestellungen nicht einsehen können.<br />
          Natürlich kannst du trotzdem eine Retoure anmelden. Wende dich bitte per E-Mail an <a href="mailto:service@horsebrands.de" style="color: #cca64b;">service@horsebrands.de</a> unter der Angabe der Bestellnummer und des Artikels, den du zurücksenden möchtest.<br />
          Wir erstellen die Retoure und du wirst benachrichtigt, sobald du dir dein Retourenlabel erstellen und ausdrucken kannst.<br />
          Vielen Dank für dein Verständnis.
        </span>
      </li>
    </ul>
  </li>
</ul>
<span style="display:none;"><?php echo $this->getPagerHtml(); ?></span>
<?php if($_orders->getSize()): ?>
<?php foreach ($_orders as $_order): ?>
<table class="data-table orders-table">
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('Order #') ?></th>
            <th><?php echo $this->__('Date') ?></th>
            <th><span class="nobr"><?php echo $this->__('Sum') ?></span></th>
            <!-- bezahlstatus? -->
            <!-- <th><span class="nobr"><?php echo $this->__('Order Status') ?></span></th> -->
            <th><span class="nobr"><?php echo $this->__('Delivery Status') ?></span></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php echo $_order->getRealOrderId() ?></td>
            <td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
            <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
            <!-- <td><?php //echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td> -->
            <!-- <td>
              <?php if(false && $_order->hasInvoices()): ?>
                <?php echo $_order->getInvoiceCollection()->getFirstItem()->getState(); ?>
              <?php endif; ?>
            </td> -->
            <td><?php echo $_order->getStatusLabel() ?></td>
            <td class="a-center">
                <span class="nobr"><a href="<?php echo $this->getViewUrl($_order) ?>" class="view-order-link"><?php echo $this->__('View Order') ?><i class="fa fa-angle-double-right"></i></a>
                    <?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
                    <?php if (false && $this->helper('sales/reorder')->canReorder($_order)) : ?>
                    <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
                <?php endif ?>
                </span>
            </td>
        </tr>
    </tbody>
</table>
<?php endforeach; ?>
<script type="text/javascript">//decorateTable('my-orders-table');</script>
<?php //echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>
