<?php $_order = $this->getOrder() ?>
<?php $returnHelper = mage::helper('ProductReturn'); ?>
<?php $returnAvailable = $returnHelper->IsOrderAvailable($_order); ?>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<div class="buttons-set">
  <p class="back-link"><a href="<?php echo $this->getUrl('sales/order/history') ?>"><small>&laquo; </small><?php echo $this->__('Back to my orders') ?></a></p>
  <?php if(is_bool($returnAvailable) && $returnAvailable): ?>
    <a href="<?php echo $returnHelper->getSelectUrl($_order); ?>" class="button right">
      <?php echo "Retoure beantragen"; ?>
    </a>
  <?php else: ?>
    <strong><?php echo $returnAvailable; ?></strong>
  <?php endif; ?>
</div>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
</div>

<?php //echo $this->getStatusHistoryRssUrl($_order) ?>
<!-- Defintiely to enable: Gets customer the chance to see invoice, shipment, creditmemo, returns -->
<dl class="order-info" style="display: none;">
    <dt><?php echo $this->__('About This Order:') ?></dt>
    <dd>
        <?php $_links = $this->getLinks(); ?>
        <ul id="order-info-tabs">
        <?php foreach ($_links as $_link): ?>
            <?php if($_link->getUrl()): ?>
                <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
            <?php else: ?>
                <li class="current"><?php echo $_link->getLabel() ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateGeneric($('order-info-tabs').select('LI'),['first','last']);</script>
    </dd>
</dl>
<!-- .end TO ENABLE -->

<div class="order-essentials">
  <dl>
    <dt><?php echo $this->__('Order Date') ?>:</dt>
    <dd><?php echo $this->formatDate($_order->getCreatedAtStoreDate(), 'long') ?></dd>
    <dt><?php echo $this->__('Customer Account Number') ?>:</dt>
    <dd><?php echo $_order->getCustomerId() ?></dd>
    <dt><?php echo $this->__('Order Status') ?>:</dt>
    <dd><?php echo $_order->getStatusLabel() ?></dd>
  </dl>
</div>

<?php echo $this->getChildHtml('sales.order.view'); ?>

<?php if (!$_order->getIsVirtual()): ?>
<div class="row order-info-box">
  <div class="columns small-12 medium-6">
      <div class="box">
          <div class="box-title">
              <h3><?php echo $this->__('Billing Address') ?></h3>
          </div>
          <div class="content">
              <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
          </div>
      </div>
  </div>
  <div class="columns small-12 medium-6">
    <div class="box">
      <div class="box-title">
        <h3><?php echo $this->__('Shipping Address') ?></h3>
      </div>
      <div class="content">
        <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
      </div>
    </div>
  </div>
</div>
<?php endif; ?>
<div class="row order-info-box">
  <div class="columns small-12 medium-6">
    <div class="box box-payment">
        <div class="box-title">
            <h3><?php echo $this->__('Payment Method') ?></h3>
        </div>
        <div class="content">
            <?php echo $this->getPaymentInfoHtml() ?>
        </div>
    </div>
  </div>
  <div class="columns small-12 medium-6">
    <div class="box">
        <div class="box-title">
            <h3><?php echo $this->__('Shipping Method') ?></h3>
        </div>
        <div class="content">
            <?php if ($_order->getShippingDescription()): ?>
                <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
            <?php else: ?>
                <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
            <?php endif; ?>
        </div>
    </div>
  </div>
</div>

<div class="row">
  <?php //$this->getChild('productreturn_list')->setOrder($_order); ?>
  <?php //echo $this->getChildHtml('productreturn_list') ?>
</div>
