<?php
  $_totals = $this->getTotals();

  $label = array(
              'discount'=>'Rabatt',
              'shipping'=>'Versand',
              'subtotal'=>'Zwischensumme',
              'grand_total'=>'Gesamtsumme',
            );

?>
<?php foreach ($_totals as $total): ?>
  <!-- <?php echo $total->getValue() ?> -->
  <?php if ($total->getBlockName()): ?>
      <?php echo $this->getChildHtml($total->getBlockName(), false); ?>
  <?php else:?>
    <div class="totals-line <?php echo ($total->getCode() == 'grand_total' ? 'totals-strong' : '') ?>">
      <?php echo $this->escapeHtml($total->getLabel());?>:
      <span class="totals-price"><?php echo $this->helper('checkout')->formatPrice( $total->getValue() ); ?></span>
      <?php if($total->getCode() == 'grand_total' && $this->helper('tax')->displayCartPriceInclTax()): ?>
        <p class="note">inkl. MwSt.</p>
      <?php elseif($total->getCode() == 'grand_total' && $this->helper('tax')->displayCartPriceExclTax()): ?>
        <p class="note">exkl. MwSt.</p>
      <?php endif; ?>
    </div>
  <?php endif; ?>
<?php endforeach; ?>
<?php /* foreach ($this->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
    <?php else:?>
    <tr class="<?php echo $_code?>">
        <td <?php echo $this->getLabelProperties()?>>
            <?php if ($_total->getStrong()):?>
            <strong><?php echo $this->escapeHtml($_total->getLabel());?></strong>
            <?php else:?>
            <?php echo $this->escapeHtml($_total->getLabel());?>
            <?php endif?>
        </td>
        <td <?php echo $this->getValueProperties()?>>
            <?php if ($_total->getStrong()):?>
            <strong><?php echo $this->formatValue($_total) ?></strong>
            <?php else:?>
            <?php echo $this->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif?>
<?php endforeach  */?>
