<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" class="img-responsive full-width" />';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
    $flashsale = $this->helper('aktionen')->getFlashsaleByCategoryId($_category->getId());
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>

<div class="category-headline deals">
  <?php if($flashsale): ?>
    <div class="row">
      <div class="columns small-12 medium-4">
        <img src="<?php echo $flashsale->getPictureUrl() ?>" alt="<?php echo $flashsale->getFsName() ?>" class="img-responsive" />
      </div>
      <div class="columns small-12 medium-8">
        <p class="fs-description">
          <?php // eigentlich alles über flashsale ?>
          <?php echo $_category->getDescription() ?>
        </p>
      </div>
    </div>
  <?php else: ?>
    <h3><?php echo $_category->getName(); ?></h3>
  <?php endif; ?>
</div>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
