<?php echo $this->getChildHtml('items_before'); ?>
<?php $_STORE_ID_SHOP = Mage::getConfig()->getNode('stores')->{'shop_de'}->{'system'}->{'store'}->{'id'}; ?>
<?php $_STORE_ID_DEALS = Mage::getConfig()->getNode('stores')->{'deals_de'}->{'system'}->{'store'}->{'id'}; ?>

<div id="checkout-review-table-wrapper">
  <div class="title-container">
    <h2><?php echo $this->__('Your Order'); ?></h2>
    <!-- <span class="cart-id">Shop</span> -->
  </div>
    <?php $_tableClass = $this->helper('tax')->displayCartBothPrices() ? 'linearize-table-large' : 'linearize-table'; ?>
    <table class="data-table <?php echo $_tableClass; ?> checkout-review-table" id="checkout-review-table">
      <colgroup>
        <col width="12.5%" />
        <col width="42.5%" />
        <col width="20%" />
        <col width="12.5%" />
        <col width="12.5%" />
      </colgroup>
        <thead>
            <tr>
              <th colspan="2" class="text-left-indent"><?php echo $this->__('Product'); ?>:</th>
              <th>&nbsp;</th>
              <th><?php echo $this->__('Qty'); ?>:</th>
              <th><?php echo $this->__('Price'); ?>:</th>
            </tr>
        </thead>
        <?php // store_id == -1: estimate shipping information for whole order ?>
        <?php $block = $this->getChild('totals')->setData('store_id', -1); ?>
        <?php echo $block->toHtml(); ?>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php echo $this->getChildHtml('items_after'); ?>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
<div id="checkout-review-submit">
    <?php echo $this->getChildHtml('agreements') ?>
    <div class="buttons-set clearfix" id="review-buttons-container">
        <?php echo $this->getChildHtml('button') ?>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Submitting order information...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submitting order information...')) ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
        <!-- <p class="f-left"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>" onclick="return confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Are you sure you want to leave this page? You will need to go through the checkout steps again.')); ?>')"><?php echo $this->__('Edit Your Cart') ?></a></p> -->
    </div>
    <script type="text/javascript">
    //<![CDATA[
        review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements'));
    //]]>
    </script>
</div>
<?php echo $this->getChildHtml('right'); ?>
