<?php
$_item = $this->getItem();
$_product = $_item->getProduct();

$manufacturer = "";
$deliverytime = "";
if($_product->getManufacturer()) $manufacturer = $_product->getAttributeText('manufacturer');
if($_product->getDeliveryTime()) $deliverytime = $_product->getAttributeText('delivery_time');
?>

<tr>
  <td class="product-image">
    <img src="<?php echo $this->getProductThumbnail()->resize(180); ?>" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>"
        class="img-responsive"/>
  </td>
  <td class="product-details">

    <div class="product-cart-manufacturer">
      <?php echo $manufacturer; ?>
    </div>
    <div class="product-name">
      <?php echo $this->escapeHtml($this->getProductName()) ?>
    </div>

    <?php // Product Options ?>
    <dl class="item-options">
      <?php if ($_options = $this->getOptionList()):?>
        <?php foreach ($_options as $_option) : ?>
        <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
            <?php if (isset($_formatedOptionValue['full_view'])): ?>
            <div class="truncated_full_value">
                <dl class="item-options">
                    <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                    <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                </dl>
            </div>
            <?php endif; ?>
        </dd>
        <?php endforeach; ?>
      <?php endif;?>
      <dt><?php echo $this->__('Qty'); ?></dt>
      <dd><?php echo $_item->getQty() ?></dd>
    </dl>

    <?php // Price ?>
    <div class="product-price">
      <?php $output = ''; ?>
      <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <?php $output = $this->helper('checkout')->formatPrice( $this->helper('checkout')->getPriceInclTax($_item) ); ?>
      <?php elseif($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <?php $output = $this->helper('checkout')->formatPrice( $_item->getCalculationPrice() ); ?>
      <?php endif; ?>
      <span>
        <strong><?php echo $output; ?></strong>
      </span>
    </div>
  </td>
</tr>
