<?php if ($this->getTotals()): ?>
  <?php $delivery_estimate = $this->getData('estimate_shipping'); ?>
  <?php $_totals = $this->getTotals(); ?>
  <?php $savedAmount = Mage::helper('horsebrands_rewrites/checkout')->getSavedAmount(); ?>
  <?php $coreHelper = $this->helper('core'); ?>

  <tr>
    <td class="text-left hide-for-medium-down">
      <?php if($delivery_estimate): ?>
        <div class="shipping-estimate-wrapper">
          <h2><?php echo $this->__('Voraussichtliche Lieferung') ?>:</h2>
          <p><?php echo $delivery_estimate; ?></p>
        </div>
      <?php endif; ?>
    </td>
    <td class="text-right totals">
      <?php foreach ($_totals as $total): ?>
        <?php if($total->getCode() == 'tax') { continue; } ?>
        <div class="<?php echo ($total->getCode() == 'grand_total' ? 'totals-strong' : '') ?>">
          <?php echo $total->getTitle() ?>:
          <span class="totals-price"><?php echo $this->helper('checkout')->formatPrice( $total->getValue() ); ?></span>
          <?php if($total->getCode() == 'grand_total' && $this->helper('tax')->displayCartPriceInclTax()): ?>
            <p class="note">inkl. MwSt.</p>
          <?php elseif($total->getCode() == 'grand_total' && $this->helper('tax')->displayCartPriceExclTax()): ?>
            <p class="note">exkl. MwSt.</p>
          <?php endif; ?>
        </div>
      <?php endforeach; ?>
      <?php if($savedAmount): ?>
        <div class="savedAmount">
          <p><?php echo $this->__('You saved %s', $coreHelper->formatPrice($savedAmount, false));  ?></p>
        </div>
      <?php endif; ?>
    </td>
  </tr>
<?php endif; ?>
