<?php
$_cartQty = $this->getSummaryCount();
if(empty($_cartQty)) {
    $_cartQty = 0;
}
?>
<div id="minicart-error-message" class="minicart-message"></div>
<div id="minicart-success-message" class="minicart-message"></div>

<div class="minicart-wrapper">

    <?php $_items = $this->getRecentItems() ?>
    <?php $countItems = count($_items); ?>
    <?php if($countItems): ?>
        <h2 class="block-title"><?php echo $this->__('Your Shopping Cart') ?></h2>
        <div>
            <ul id="cart-sidebar" class="mini-products-list">
                <?php foreach($_items as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach; ?>
            </ul>
        </div>
        <script type="text/javascript">
            truncateOptions();
            decorateList('cart-sidebar', 'none-recursive');
            $j('document').ready(function() {
                var minicartOptions  = {
                    formKey:           "<?php echo $this->getFormKey();?>"
                }
                var Mini = new Minicart(minicartOptions);
                Mini.init();
            });
        </script>

        <div id="minicart-widgets">
            <?php echo $this->getChildHtml('cart_promotion') ?>
        </div>
        <div class="block-content">
          <div class="right-col">
            <span class="mini-cart-totals-label"><?php echo $this->__('Subtotal') ?>:</span>
            <span class="mini-cart-totals-value"><?php echo Mage::helper('checkout')->formatPrice($this->getSubtotalInclTax()) ?></span>
            <p class="note"><?php echo $this->__('incl. VAT') ?></p>
          </div>
        </div>


        <div class="minicart-actions">
          <div class="right-col">
            <a class="cart-link button gold expand default-size" href="<?php echo $this->getUrl('checkout/cart'); ?>">
              <?php echo $this->__('View Shopping Cart'); ?>
            </a>
          </div>
        </div>

    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>

    <?php endif ?>
</div>
