<div class="account-login">
  <?php echo $this->getMessagesBlock()->toHtml() ?>
  <?php echo $this->getChildHtml('customer.form.login.extra')?>

  <div class="row full-width small-margins">
    <div class="columns small-12 medium-6">
      <div class="box">
        <h2 class="title">Ich bin bereits Horsebrands-Kunde <i class="fa fa-lock"></i></h2>
        <div class="content clearfix">
          <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <div class="kv">
              <div class="key">
                <label for="email">E-Mail</label>
              </div>
              <div class="value">
                <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" />
              </div>
            </div>
            <div class="kv">
              <div class="key">
                <label for="pass">Passwort</label>
              </div>
              <div class="value">
                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" />
              </div>
            </div>
            <div class="kv">
              <div class="key">
                &nbsp;
              </div>
              <div class="value">
                <a href="#login" class="btn medium orange right" onclick="$j('#login-form').submit();return false;">Einloggen ></a>
              </div>
            </div>
          <?php echo $this->getChildHtml('form.additional.info'); ?>
          </form>
        </div>
      </div>
    </div>
    <div class="columns small-12 medium-6">
      <div class="box">
        <?php echo $this->getChildHtml('registration'); ?>
      </div>
    </div>
  </div>
  <script type="text/javascript">
  //<![CDATA[
      var dataForm = new VarienForm('login-form', true);
      var registerForm = new VarienForm('form-validate', true);
  //]]>
  </script>
</div>

<?php
/*
<h2 class="title">Ich bin Neukunde <i class="fa fa-lock"></i></h2>
<form action="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'shop_de/customer/account/createpost'; ?>" method="post" id="form-validate">
<div class="content clearfix">
  <table class="unstyled">
    <colgroup>
      <col width="15%"/>
      <col width="85%"/>
    </colgroup>
    <tbody>
      <tr>
        <td class="text-left">
          <label>E-Mail<em>*</em></label>
        </td>
        <td>
          <input type="text" class="full-width" />
        </td>
      </tr>
      <tr>
        <td class="text-left">
          <label>Passwort<em>*</em></label>
        </td>
        <td>
          <input type="text" class="full-width" />
        </td>
      </tr>
      <tr>
        <td class="text-left">
          <label class="note">Passwort<em>*</em><span>(Wiederholen)</span></label>
        </td>
        <td class="align-base">
          <input type="text" class="full-width" />
        </td>
      </tr>
      <tr>
        <td class="text-left small-spacing">
          &nbsp;
        </td>
        <td class="text-left small-spacing">
          <label class="checkbox full-width">
            <input type="checkbox" class="checkbox besides" />
            <div class="cb-text">
              Ja, ich stimme den AGB und den Datenschutzbestimmungen von Horsebrands sowie einer Bonitätsprüfung zu.<em>*</em>
            </div>
          </label>
        </td>
      </tr>
      <tr>
        <td class="text-left">
          &nbsp;
        </td>
        <td class="text-left">
          <label class="checkbox full-width">
            <input type="checkbox" class="checkbox besides" />
            <div class="cb-text">
              Ja, ich m&ouml;chte &uuml;ber Trends, Aktionen, & Gutscheine per E-Mail informiert werden. Abmeldung jederzeit m&ouml;glich.
            </div>
          </label>
        </td>
      </tr>
      <tr>
        <td class="align-bottom">
          <p class="note left">
            <em>*</em>Pflichtangaben
          </p>
        </td>
        <td>
          <button type="submit" class="btn medium orange right">Kostenlos registrieren ></button>
        </td>
      </tr>
    </tbody>
  </table>
</div>
</form>

*/
 ?>
