<div class="account-login">
  <?php echo $this->getMessagesBlock()->toHtml() ?>
  <?php echo $this->getChildHtml('customer.form.login.extra')?>

  <div class="row full-width small-margins">
    <div class="columns small-12 medium-6">
      <div class="box">
        <h2 class="title">Ich bin bereits Horsebrands-Kunde <i class="fa fa-lock"></i></h2>
        <div class="content clearfix">
          <form id="login-form" action="<?php echo $this->getPostActionUrl() ?>" method="post">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <div class="input-container label-aside">
              <div class="input-block">
                <label>E-Mail-Adresse</label>
                <input type="text" class="full-width input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
              </div>
              <div class="input-block">
                <label>Passwort</label>
                <input type="password" class="full-width input-text required-entry" id="login-password" name="login[password]" />
              </div>
              <div class="input-block checkbox">
                <div class="right-col">
                  <input type="checkbox" name="privacy_policy" value="1" title="<?php echo $this->__('Accept the privacy policy') ?>" class="checkbox required-entry">
                  <label class="smaller">Ja, ich stimme den <a class="condition" href="<?php echo $this->getUrl('agb'); ?>" target="_blank">AGB</a> und den <a class="condition" href="<?php echo $this->getUrl('datenschutz'); ?>" target="_blank">Datenschutzbestimmungen</a> von Horsebrands zu.</label>
                </div>
              </div>
              <div class="buttons-container">
                <button type="submit" class="btn gold medium width-l right">Einloggen ></button>
              </div>
            </div>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
          </form>
        </div>
      </div>
    </div>
    <div class="columns small-12 medium-6">
      <div class="box">
        <?php echo $this->getChildHtml('registration'); ?>
      </div>
    </div>
  </div>
  <script type="text/javascript">
  //<![CDATA[
      var dataForm = new VarienForm('login-form', true);
      var registerForm = new VarienForm('form-validate', true);
  //]]>
  </script>
</div>
