<?php $_order = $this->getOrder(); ?>

<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
    <?php $_itemCount = count($_items); ?>
    <tr>
      <td class="inner contents">
        <table class="items" cellpadding="0" cellspacing="0" border="0">
          <colgroup>
            <col width="60%" />
            <col />
            <col />
          </colgroup>
          <thead>
              <tr>
                  <th class="cell-name align-left">
                    <?php echo $this->__('Products'); ?>
                  </th>
                  <th class="cell-name align-center">
                      <?php echo $this->__('Qty'); ?>
                  </th>
                  <th class="cell-name align-right">
                      <?php echo $this->__('Price'); ?>
                  </th>
              </tr>
          </thead>
          <?php $i=0; foreach ($_order->getAllItems() as $_item): ?>
          <?php if($_item->getParentItem()) continue; else $i++; ?>
            <?php echo $this->getItemHtml($_item) ?>
          <?php endforeach; ?>
        </table>
      </td>
    </tr>
    <tr>
        <td class="inner contents">
            <?php echo $this->getChildHtml('order_totals') ?>
        </td>
    </tr>
<?php endif; ?>
