<?php
    $_cartQty = $this->getSummaryCount();
    if(empty($_cartQty)) {
        $_cartQty = 0;
    }
?>

<div class="dropdown-tab" style="z-index: 30;">
  <a href="" onclick="redirectOnMobile('<?php echo $this->getUrl('checkout/cart') ?>'); return false;">
  <div class="icon shoppingcart">
    <span class="count">(<?php echo $_cartQty; ?>)</span>
    <span><?php echo $this->__('Warenkorb'); ?></span>
  </div>
  </a>
</div>
<div class="dropdown-content minicart-dropdown" style="z-index: 25;">
  <?php echo $this->getChildHtml('minicart_content');?>
</div>
