<?php
    $_cartQty = $this->getSummaryCount();
    if(empty($_cartQty)) {
        $_cartQty = 0;
    }
?>

<div class="dropdown-tab" style="z-index: 30;">
  <div class="icon shoppingcart">
    <span class="count">(<?php echo $_cartQty; ?>)</span>
    <span><?php echo $this->__('Warenkorb'); ?></span>
  </div>
</div>
<div class="dropdown-content minicart-dropdown" style="z-index: 25;">
  <?php echo $this->getChildHtml('minicart_content');?>
</div>

<?php /*
<a href="<?php echo $this->helper('checkout/cart')->getCartUrl(); ?>" data-target-element="#header-cart" class="skip-link skip-cart <?php if($_cartQty <= 0): ?> no-count<?php endif; ?>">
    <span class="icon"></span>
    <span class="label"><?php echo $this->__('Cart'); ?></span>
    <span class="count"><?php echo $_cartQty; ?></span>
</a>

<div id="header-cart" class="block block-cart skip-content">
    <?php echo $this->getChildHtml('minicart_content');?>
</div>
*/ ?>
