<?php
  $_items = $this->getTotalItems();
  $_subtotal = 0;
  $_totals = $this->getTotals();

  $label = array(
            'discount'=>'Rabatt',
            'shipping'=>'Versand',
            'subtotal'=>'Zwischensumme',
            'tax'=>'19% Mwst.',
            'grand_total'=>'Gesamtsumme',
          );

  if($_items){
    foreach ($_items as $item) {
      $_subtotal += $item->getPriceInclTax() * $item->getQty();
    }
  }
?>

<?php if($_items): ?>
  <dl class="totals-block">
    <dt>
      <?php echo $this->__('Subtotal') ?>:
      <p class="note"><?php echo $this->__('incl. VAT') ?></p>
    </dt>
    <dd>
      <?php echo $this->helper('checkout')->formatPrice( $_subtotal ); ?>
    </dd>
  </dl>
<?php else: ?>
  <dl class="totals-block">
    <?php foreach ($_totals as $total): ?>
      <?php // skip tax declaration ?>
      <?php if($total->getCode() == 'tax') { continue; } ?>
      <?php $isGrandTotal = ($total->getCode() == 'grand_total') ?>
    <dt<?php echo ($isGrandTotal ? ' class="totals-strong"' : '') ?>>
      <?php echo $label[$total->getCode()] ?>:
      <?php if($total->getCode() == 'grand_total' && $this->helper('tax')->displayCartPriceInclTax()): ?>
        <p class="note">(<?php echo $this->__('incl. VAT') ?>)</p>
      <?php elseif($total->getCode() == 'grand_total' && $this->helper('tax')->displayCartPriceExclTax()): ?>
        <p class="note">(<?php echo $this->__('excl. VAT') ?>)</p>
      <?php endif; ?>
    </dt>
      <dd class="totals-price<?php echo ($isGrandTotal ? ' totals-strong' : '') ?>">
        <?php echo $this->helper('checkout')->formatPrice( $total->getValue() ); ?>
      </dd>
    <?php endforeach; ?>
  </dl>
<?php endif; ?>
<?php $this->setTotalItems(null); ?>
