<?php if (!Mage::registry('current_category')) return ?>
<?php $_categories = $this->getCurrentChildCategories() ?>
<?php $_count = is_array($_categories)?count($_categories):$_categories->count(); ?>
<?php if($_count): ?>
<div class="block block-layered-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Browse By') ?></span></strong>
    </div>
    <div class="block-content">
        <dl id="narrow-by-list2">
            <dt class="title"><?php echo $this->__('Category') ?></dt>
            <dd>
                <ul>
                <?php foreach ($_categories as $_category): ?>
                    <?php if($_category->getIsActive()): ?>
                    <?php $subCatHtml = $this->getNextLayerHtml($_category) ?>
                    <li>
                        <a href="<?php echo $this->getCategoryUrl($_category) ?>" class="first <?php if ($this->isCategoryActive($_category)): ?> current<?php endif; ?>">
                          <?php echo $this->escapeHtml($_category->getName()) ?><i class="fa fa-chevron-<?php echo ($subCatHtml ? 'down' : 'right') ?>"></i>
                        </a>
                        <?php if( $subCatHtml && $subCatHtml != '' ): ?>
                          <ul class="subcat-layer">
                            <?php echo $subCatHtml; ?>
                          </ul>
                        <?php endif; ?>
                    </li>
                    <?php endif; ?>
                <?php endforeach ?>
                </ul>
            </dd>
        </dl>
        <script type="text/javascript">decorateDataList('narrow-by-list2')</script>
    </div>
</div>
<?php endif; ?>
<div class="seo-text">
  <?php echo Mage::registry('current_category')->getDescription(); ?>
</div>
