<?php if (!Mage::registry('current_category')) return ?>
<?php $_categories = $this->getCurrentChildCategories() ?>
<?php $_count = is_array($_categories)?count($_categories):$_categories->count(); ?>
<?php if($_count): ?>
<div class="block block-layered-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Browse By') ?></span></strong>
    </div>
    <div class="block-content">
        <dl id="narrow-by-list2">
            <dt class="title"><?php echo $this->__('Category') ?></dt>
            <dd>
                <ul class="first-level">
                <?php foreach ($_categories as $_category): ?>
                    <?php if($_category->getIsActive()): ?>
                    <?php $subCatHtml = $this->getNextLayerHtml($_category) ?>
                    <li>
                        <a href="<?php echo $this->getCategoryUrl($_category) ?>" class="childcategory-header first <?php if ($this->isCategoryActive($_category)): ?> current<?php endif; ?>">
                          <?php echo $this->escapeHtml($_category->getName()) ?><i class="fa fa-chevron-right"></i>
                        </a>
                        <?php if( $subCatHtml && $subCatHtml != '' ): ?>
                          <ul class="subcat-layer hide">
                            <?php echo $subCatHtml; ?>
                          </ul>
                        <?php endif; ?>
                    </li>
                    <?php endif; ?>
                <?php endforeach ?>
                </ul>
            </dd>
        </dl>
        <script type="text/javascript">decorateDataList('narrow-by-list2')</script>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
jQuery(document).ready(function($) {
  $('.childcategory-header').click(function(e) {
    e.preventDefault();

    var $this = $(this);
    if( $this.hasClass('expanded') ) {
      $this.removeClass('expanded');
      $this.children('.fa').removeClass('fa-chevron-down').addClass('fa-chevron-right');
      $this.siblings('.subcat-layer').addClass('hide');
    } else {
      $this.addClass('expanded');
      $this.children('.fa').removeClass('fa-chevron-right').addClass('fa-chevron-down');
      $this.siblings('.subcat-layer').removeClass('hide');
    }
  });
});
//]]>
</script>
<?php endif; ?>
<div class="seo-text">
  <?php echo Mage::registry('current_category')->getDescription(); ?>
</div>
