
<form id="co-address-form" method="post">
<div class="row full-width small-margins">
  <div class="columns small-12 medium-6">
      <div class="box" id="billingcontent">
        <h2 class="title"><?php echo $this->__('Billing Address'); ?></h2>
        <div class="content clearfix">
            <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
            <?php if (false && $this->customerHasAddresses()): ?>
                <li class="wide">
                    <label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
                    <div class="input-box">
                        <?php echo $this->getAddressesHtmlSelect('billing') ?>
                    </div>
                </li>
            <?php endif; ?>
            <div class="customer-address">
              <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
              <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('Street'); ?><em>*</em></label>
                </div>
                <div class="value">
                  <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                  <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                  <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                  <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                  <?php endfor; ?>
                </div>
              </div>
              <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('c/o'); ?></label>
                </div>
                <div class="value">
                  <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" onchange="shipping.setSameAsBilling(false);" />
                </div>
              </div>
              <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('Post Code'); ?><em>*</em></label>
                </div>
                <div class="value">
                  <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                </div>
              </div>
              <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('City'); ?><em>*</em></label>
                </div>
                <div class="value">
                  <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="billing:city" />
                </div>
              </div>
              <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('Country'); ?><em>*</em></label>
                </div>
                <div class="value">
                  <?php echo $this->getCountryHtmlSelect('billing') ?>
                </div>
              </div>
              <div class="kv">
                <div class="key">
                  <label for="billing:telephone"><em>*</em><?php echo $this->__('Telephone') ?></label>
                </div>
                <div class="value">
                  <input type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" />
                </div>
              </div>
              <input type="hidden" name="billing[save_in_address_book]" value="1" />
              <div class="same-as-billing-container">
                <?php if ($this->canShip()): ?>
                  <input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping" value="0" title="<?php echo $this->__('Ship to different address') ?>"  class="radio" /><label for="billing:use_for_shipping_no">&nbsp;<?php echo $this->__('Ship to different address') ?></label>
                  <!-- <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo  Mage::helper('core')->quoteEscape($this->__('Ship to this address')) ?>" onclick="$('shipping:same_as_billing').checked = true;" class="radio" /><label for="billing:use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label> -->
                  <!-- <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0"<?php if (!$this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo Mage::helper('core')->quoteEscape($this->__('Ship to different address')) ?>" onclick="$('shipping:same_as_billing').checked = false;" class="radio" /><label for="billing:use_for_shipping_no"><?php echo $this->__('Ship to different address') ?></label> -->
                <?php endif; ?>
                <?php if (!$this->canShip()): ?>
                    <input type="hidden" name="billing[use_for_shipping]" value="1" />
                <?php endif; ?>
              </div>
        </div>
      </div>
    </div>
  </div>
  <div class="columns small-12 medium-6">
    <?php echo $this->getChildHtml('address.shipping'); ?>
  </div>
</div>
<div class="buttons-set clearfix" id="billing-buttons-container">
  <button class="left" onclick="checkout.back(); return false;"><i class="fa fa-angle-double-left"></i> <?php echo $this->__('Back'); ?></button>
  <button class="gold right" id="btnBillingContinue" type='button'><?php echo $this->__('Continue'); ?> <i class="fa fa-angle-double-right"></i></button>
  <span class="please-wait" id="billing-please-wait" style="display:none;">
    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
  </span>
</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var billing = new Billing('co-address-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-address-form');

    var shipping = new Shipping('co-address-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>');
    var shippingForm = new VarienForm('co-address-form');

    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    jQuery(document).ready(function ($j) {

        if($j('#shippingcontent').find('input').hasClass('validation-failed')) {
            $j('input:checkbox[name="billing[use_for_shipping]"]').prop('checked');
            $j('#shippingcontent').show(100);
        }

        $j('input:checkbox[name="billing[use_for_shipping]"]').change(function () {
            $j('#shippingcontent').toggle(100);
            $j('#same-as-billing-text').toggle(100);
        });

        $j('#btnBillingContinue').on('click', function () {
          console.log('bounce');
          var useforshipping = $j('input:checkbox[id="billing:use_for_shipping"]:checked').val();
          if (useforshipping == null) {
            console.log('null');
            if ($j('input:text[name="shipping[street][]"]').val() == '' ||
                $j('input:text[name="shipping[street][]"]').val() != $j('input:text[name="billing[street][]"]').val()){
                var billingaddress = $j('input:text[name="billing[street][]"]').val();
                $j('input:text[name="shipping[street][]"]').val(billingaddress);
            }
            if ($j('input:text[name="shipping[city]"]').val() == '' ||
                $j('input:text[name="shipping[city]"]').val() != $j('input:text[name="billing[city]"]').val()) {
                var billingcity = $j('input:text[name="billing[city]"]').val();
                $j('input:text[name="shipping[city]"]').val(billingcity);
            }
            if ($j('input:text[name="shipping[postcode]"]').val() == '' ||
                $j('input:text[name="shipping[postcode]"]').val() != $j('input:text[name="billing[postcode]"]').val()) {
                var billingpostcode = $j('input:text[name="billing[postcode]"]').val();
                $j('input:text[name="shipping[postcode]"]').val(billingpostcode);
            }
            if ($j('select[name="shipping[country_id]"]').val() == '' ||
                $j('select[name="shipping[country_id]"]').val() != $j('select[name="billing[country_id]"]').val()) {
                var billingcountryid = $j('select[name="billing[country_id]"]').val();
                $j('select[name="shipping[country_id]"]').val(billingcountryid).change();
                if(billingcountryid != 'DE') {
                    //$j('input:text[name="shipping[postcode]"]').removeClass('hb-validate-zipcode');
                }
            }

            billing.save();
          } else {
            console.log('not null');
            shipping.save();
          }
        });
    });
//]]>
</script>
