
<div class="row full-width small-margins">
  <div class="columns small-12 medium-6">
      <div class="box">
        <h2 class="title"><?php echo $this->__('Billing Address'); ?></h2>
        <div class="content clearfix">
          <form id="co-billing-form" action="">
            <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
            <?php if ($this->customerHasAddresses()): ?>
                <li class="wide">
                    <label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
                    <div class="input-box">
                        <?php echo $this->getAddressesHtmlSelect('billing') ?>
                    </div>
                </li>
            <?php endif; ?>
            <div class="customer-address">
              <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
              <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('Street'); ?><em>*</em></label>
                </div>
                <div class="value">
                  <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                  <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                  <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                  <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                  <?php endfor; ?>
                </div>
              </div>
              <!-- <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('c/o'); ?><em>*</em></label>
                </div>
                <div class="value">

                </div>
              </div> -->
              <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('Post Code'); ?><em>*</em></label>
                </div>
                <div class="value">
                  <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                </div>
              </div>
              <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('City'); ?><em>*</em></label>
                </div>
                <div class="value">
                  <input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="billing:city" />
                </div>
              </div>
              <div class="kv">
                <div class="key">
                  <label><?php echo $this->__('Country'); ?><em>*</em></label>
                </div>
                <div class="value">
                  <?php echo $this->getCountryHtmlSelect('billing') ?>
                </div>
              </div>
              <div class="same-as-billing-container">
                <?php if ($this->canShip()): ?>
                  <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo  Mage::helper('core')->quoteEscape($this->__('Ship to this address')) ?>" onclick="$('shipping:same_as_billing').checked = true;" class="radio" /><label for="billing:use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label>
                  <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0"<?php if (!$this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo Mage::helper('core')->quoteEscape($this->__('Ship to different address')) ?>" onclick="$('shipping:same_as_billing').checked = false;" class="radio" /><label for="billing:use_for_shipping_no"><?php echo $this->__('Ship to different address') ?></label>
                <?php endif; ?>
                <?php if (!$this->canShip()): ?>
                    <input type="hidden" name="billing[use_for_shipping]" value="1" />
                <?php endif; ?>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="columns small-12 medium-6">
    <?php //echo $this->getChildHtml('address.shipping'); ?>
    <!-- <div class="box">
      <h2 class="title"><?php echo $this->__('Shipping Address'); ?></h2>
      <div class="content clearfix">
        CONTENT
      </div>
    </div> -->
  </div>
</div>
<div class="buttons-set clearfix">
  <button class="left" onclick="checkout.back(); return false;"><i class="fa fa-angle-double-left"></i> <?php echo $this->__('Back'); ?></button>
  <button class="gold right" onclick="billing.save(); return false;"><?php echo $this->__('Continue'); ?> <i class="fa fa-angle-double-right"></i></button>
</div>
<span class="please-wait" id="billing-please-wait" style="display:none;">
  <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
</span>
<script type="text/javascript">
//<![CDATA[
    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');

    //billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Select State/Province...')) ?>');
    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);

    // var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
    if ($('onepage-guest-register-button')) {
        Event.observe($('onepage-guest-register-button'), 'click', function(event) {
            var billingRememberMe = $('co-billing-form').select('#remember-me-box');
            if (billingRememberMe.length > 0) {
                if ($('login:guest') && $('login:guest').checked) {
                    billingRememberMe[0].hide();
                } else if ($('login:register') && ($('login:register').checked || $('login:register').type == 'hidden')) {
                    billingRememberMe[0].show();
                }
            }
        });
    }
//]]>
</script>
