<div class="row full-width small-margins">
  <div class="columns small-12 medium-6">
    <div class="box">
      <h2 class="title">Bereits Horsebrands-Kunde?</h2>
      <div class="content clearfix">
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
          <input type="hidden" name="success_url" value="<?php echo $this->getUrl('checkout/onepage') ?>" />
          <input type="hidden" name="error_url" value="<?php echo $this->getUrl('checkout/onepage') ?>" />
          <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
          <div class="input-container label-aside">
            <div class="input-block">
              <label><?php echo $this->__('E-Mail-Address') ?><em>*</em></label>
              <input type="text" class="full-width input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
            </div>
            <div class="input-block">
              <label><?php echo $this->__('Password') ?><em>*</em></label>
              <input type="password" class="full-width input-text required-entry" id="login-password" name="login[password]" />
            </div>
            <div class="input-block">
              <label>&nbsp;</label>
              <a style="width:75%; line-height: 1.6" href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>">
                <?php echo $this->__('Forgot Password') ?>?
              </a>
            </div>
            <?php /* <div class="input-block checkbox">
              <div class="right-col">
                <input type="checkbox" name="privacy_policy" value="1" title="<?php echo $this->__('Accept the privacy policy') ?>" class="checkbox required-entry">
                <label class="smaller">Ja, ich stimme den <a class="condition" href="<?php echo $this->getUrl('agb'); ?>" target="_blank">AGB</a> und den <a class="condition" href="<?php echo $this->getUrl('datenschutz'); ?>" target="_blank">Datenschutzbestimmungen</a> von Horsebrands zu.</label>
              </div>
            </div> */ ?>
            <div class="buttons-container" style="text-align: right;">
              <button class="gold" onclick="onepageLogin(this);return false;">Einloggen ></button>
              <?php echo $this->getLayout()->createBlock('inchoo_socialconnect/facebook_button')->setTemplate('inchoo/socialconnect/facebook/button.phtml')->toHtml(); ?>
            </div>
          </div>
          <?php echo $this->getChildHtml('form.additional.info'); ?>
        </form>
      </div>
    </div>
  </div>
  <div class="columns small-12 medium-6">
    <div class="box">
      <h2 class="title">Neu bei Horsebrands?</h2>
      <div class="content clearfix">
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
          <div class="buttons-container" style="margin-top: 1rem;">
            <button class="gold" onclick="checkout.setMethod();" style="padding: 0 1rem;"><?php echo $this->__('Registriere dich während des Checkouts') ?> ></button>
          </div>
        <?php else: ?>
          <p>Der Gast-Checkout ist nicht erlaubt.</p>
        <?php endif; ?>
      </div>
    </div>
  </div>
</div>
<input type="hidden" name="checkout_method" id="login:guest" value="guest" checked="checked" />
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    var regForm = new VarienForm('register-form', true);

    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(element) {
      if(loginForm.validator && loginForm.validator.validate()){
          loginForm.submit();
      }
    }
//]]>
</script>
