<div class="row full-width small-margins">
  <div class="columns small-12 medium-6">
    <div class="box">
      <h2 class="title">Ich bin bereits Horsebrands-Kunde <i class="fa fa-lock"></i></h2>
      <div class="content clearfix">
        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
          <?php echo $this->getBlockHtml('formkey'); ?>
          <div class="kv">
            <div class="key">
              <label for="email">E-Mail</label>
            </div>
            <div class="value">
              <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" />
            </div>
          </div>
          <div class="kv">
            <div class="key">
              <label for="pass">Passwort</label>
            </div>
            <div class="value">
              <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" />
            </div>
          </div>
          <div class="kv">
            <div class="key">
              &nbsp;
            </div>
            <div class="value">
              <a href="#login" class="btn large orange right" onclick="onepageLogin(this);return false;">Einloggen ></a>
            </div>
          </div>
        <?php echo $this->getChildHtml('form.additional.info'); ?>
        </form>
      </div>
    </div>
  </div>
  <div class="columns small-12 medium-6">
    <div class="box">
      <?php echo $this->getChildHtml('registration'); ?>
    </div>
  </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(element)
    {
      if(loginForm.validator && loginForm.validator.validate()){
          // button.disabled = true;
          loginForm.submit();
      }
    }
//]]>
</script>
