<?php $_shipment = $this->getShipment() ?>
<?php $_order = $this->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
  <?php $i=0; foreach ($_shipment->getAllTracks() as $_item): $i++ ?>
  <div>
    <p><?php echo $this->escapeHtml($_item->getNumber()) ?></p>
    <a href="http://nolp.dhl.de/nextt-online-public/set_identcodes.do?lang=de&idc=<?php echo $_item->getNumber() ?>">
      Sendungsverfolgung ansehen
    </a>
  </div>
  <?php endforeach ?>
<?php endif; ?>
