<footer>
  <div class="container footer-container clearfix">
    <div class="row">
      <div class="columns medium-2 footer-col-main">
        <h1>Horsebrands</h1>
        <ul class="unstyled">
          <li><a href="#">Jobs</a></li>
          <li><a href="#">Magazin</a></li>
          <li><a href="#">Unser Versprechen</a></li>
          <li><a href="#">Presse</a></li>
          <li><a href="#">Impressum</a></li>
          <li><a href="#">Datenschutz</a></li>
          <li><a href="#">AGB</a></li>
        </ul>
      </div>
      <div class="columns medium-2 footer-col-contact">
        <h1>Kundenservice</h1>
        <ul class="unstyled">
          <li><a href="#">Kontakt</a></li>
          <li><a href="#">Versandarten</a></li>
          <li><a href="#">Zahlungsarten</a></li>
          <li><a href="#">Umtausch & R&uuml;cksendungen</a></li>
          <li><a href="#">Geschenkgutschein</a></li>
          <li><a href="#">FAQ</a></li>
        </ul>
      </div>
      <div class="columns medium-2 end footer-col-social">
        <h1>Verbinden</h1>
        <ul class="unstyled">
          <li><a href="#">Facebook</a></li>
          <li><a href="#">Instagram</a></li>
          <li><a href="#">Youtube</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
