<?php $currentStoreId = Mage::app()->getStore()->getId(); ?>
<?php $_STORE_ID_SHOP = Mage::getConfig()->getNode('stores')->{'shop_de'}->{'system'}->{'store'}->{'id'}; ?>
<?php $_STORE_ID_DEALS = Mage::getConfig()->getNode('stores')->{'deals_de'}->{'system'}->{'store'}->{'id'}; ?>
<header>
  <?php $toplineblock = $this->getChild('topline.content'); ?>
  <?php if($toplineblock->getIsActive()): ?>
  <div class="fixed-top hide-for-small-down">
    <div class="container">
      <?php echo $toplineblock->toHtml(); ?>
    </div>
  </div>
  <?php endif; ?>
  <div class="top-header container clearfix">
    <div class="top-header-element top-header-left store-select">
      <a href="<?php echo Mage::app()->getStore(intval($_STORE_ID_SHOP))->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>" class="store-button<?php echo ($currentStoreId == $_STORE_ID_SHOP ? ' active' : '') ?>">
        Shop
      </a>
      <a href="<?php echo Mage::app()->getStore(intval($_STORE_ID_DEALS))->getUrl('aktionen'); ?>" class="store-button<?php echo ($currentStoreId == $_STORE_ID_DEALS ? ' active' : '') ?>">
        Deals
        <span class="ic-deals-fahne" style="<?php echo ($currentStoreId == $_STORE_ID_DEALS ? 'display: none;' : '') ?>">
          &nbsp;
        </span>
      </a>
    </div>
    <div class="top-header-element top-header-center brand">
      <div class="logo-wrapper small-5 medium-12">
        <a href="<?php echo $this->getBaseUrl() ?>" class="logo-link">
          <img src="<?php echo $this->getLogoSrc() ?>" class="img-responsive">
        </a>
      </div>
      <div id="mobile-search-wrapper" class="search-wrapper small-7 hide-for-medium-up">
        <div class="mobile-search-wrapper">
          <?php echo $this->getChildHtml('topSearch'); ?>
        </div>
      </div>
    </div>
    <div class="top-header-element top-header-right customer-nav">
      <div class="customer-nav-container">
        <ul class="customer-nav-list offcanvas-elements">
          <li class="customer-nav-element hide-for-medium-up">
            <div class="dropdown-tab">
              <a class="toggle-nav" id="mobile-menu-button">
                <div class="icon mobile-menu">
                  <span><?php echo $this->__('Menu'); ?></span>
                </div>
                <p></p>
              </a>
            </div>
          </li>
          <?php if(!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
          <li class="customer-nav-element">
            <div class="dropdown-tab">
              <a href="" onclick="redirectOnMobile('<?php echo $this->getUrl('customer/account') ?>'); return false;">
                <div class="icon customeraccount">
                  <span><?php echo $this->__('Anmelden'); ?></span>
                </div>
              </a>
            </div>
            <div class="dropdown-content">
              <?php echo $this->getChildHtml('customer.login') ?>
            </div>
          </li>
          <?php else: ?>
            <li class="customer-nav-element">
              <div class="dropdown-tab">
                <a href="<?php echo $this->getUrl('customer/account') ?>">
                  <div class="icon customeraccount loggedin">
                    <span><?php echo $this->__('Mein Konto'); ?></span>
                  </div>
                </a>
              </div>
              <div class="dropdown-content">
                <?php echo $this->getChildHtml('topLinks') ?>
              </div>
            </li>
          <?php endif; ?>
          <li class="customer-nav-element">
            <div class="dropdown-tab">
              <a href="<?php echo $this->getUrl('wishlist') ?>">
                <div class="icon wishlist">
                  <span><?php echo $this->__('Wishlist'); ?></span>
                </div>
              </a>
            </div>
            <div class="dropdown-content" style="display:none;">
              Wunschzettelinhalte
            </div>
          </li>
          <li class="customer-nav-element">
            <?php echo $this->getChildHtml('minicart_head'); ?>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <?php if($currentStoreId == $_STORE_ID_SHOP): ?>
    <div class="navbar container clearfix">
      <ul class="nav">
        <?php echo $this->getChildHtml('topMenu'); ?>
      </ul>
      <div class="global-search">
        <?php echo $this->getChildHtml('topSearch'); ?>
      </div>
    </div>
  <?php endif; ?>

  <script type="text/javascript">
  //<![CDATA[
    jQuery(document).ready(function($) {
      $('#mobile-search-wrapper #search').focusin(function(e) {
        $('#mobile-search-wrapper').addClass('spread');
      });
      $('#mobile-search-wrapper #search').focusout(function(e) {
        $('#mobile-search-wrapper').removeClass('spread');
      });
    });

  //]]>
  </script>
</header>
