<section id="promise">
  <h5 class="section-title">&nbsp;</h5>
  <div class="row full-width smaller-margins">
    <div class="columns medium-8">
      <div class="row full-width smaller-margins">
        <div class="columns medium-12 no-padding">
          <div class="box newsletter-box">
            <h2 class="title">Horsebrands Newsletter</h2>
            <div class="content" style="padding: 0;">
              <div class="newsletter-discount">
                <div class="circle" style="display: table;">
                  <div>
                    <span>5 €</span><br/>Gutschein
                  </div>
                </div>
              </div>
              <div class="newsletter-text">
                <table class="unstyled">
                  <tbody>
                    <tr>
                      <td class="title">
                        Newsletter |
                      </td>
                      <td class="desc">
                        Abonniere unseren Newsletter<br/>
                        & du erh&auml;lst von uns einen 5€ Gutschein
                      </td>
                    </tr>
                  </tbody>
                </table>
                <form id="newsletter-subscribe">
                  <input name="email" type="text" placeholder="Deine E-Mail-Adresse..." />
                  <a class="btn small orange">Abonnieren</a>
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="columns medium-7 new-inner-row">
          <div class="box">
            <h2 class="title">Zahlungsarten</h2>
            <div class="content">
              <ul class="unstyled inline same-width">
                <li>MC</li>
                <li>Visa</li>
                <li>AmEx</li>
                <li>Paypal</li>
                <li>Sofort</li>
                <li>Lastschrift</li>
              </ul>
            </div>
          </div>
        </div>
        <div class="columns medium-5">
          <div class="box">
            <h2 class="title">Versandarten</h2>
            <div class="content">
              <ul class="unstyled inline same-width">
                <li>DHL</li>
                <li>DHL</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="columns medium-4">
      <div class="box">
        <h2 class="title">Unser Versprechen</h2>
        <div class="content">
          <ul class="unstyled check-items">
            <li>14 Tage R&uuml;ckgaberecht</li>
            <li>Versandkostenfrei ab einem Bestellwert von 30€</li>
            <li>Kostenloser Kundenservice</li>
            <li>Schnelle Lieferzeiten</li>
            <li>K&auml;ufer- & Datenschutz</li>
            <li>Sichere Zahung mit SSL-Verschl&uuml;sselung</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
