<?php $_STORE_ID_SHOP = Mage::getConfig()->getNode('stores')->{'shop_de'}->{'system'}->{'store'}->{'id'}; ?>
<?php $_STORE_ID_DEALS = Mage::getConfig()->getNode('stores')->{'deals_de'}->{'system'}->{'store'}->{'id'}; ?>
<?php $_menu = $this->getHtml('level-top') ?>

<div class="offcanvas-menu-wrapper">
  <h1>
    <a href="<?php echo Mage::app()->getStore(intval($_STORE_ID_SHOP))->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>">
      <?php echo $this->__('Shop')?>
    </a>
  </h1>
  <?php if($_menu && Mage::app()->getStore()->getId() == $_STORE_ID_SHOP): ?>
    <ul>
      <?php echo $_menu ?>
    </ul>
  <?php endif ?>
  <div class="divider white"></div>
  <h1>
    <a href="<?php echo Mage::app()->getStore(intval($_STORE_ID_DEALS))->getUrl('aktionen'); ?>">
      <?php echo $this->__('Deals')?>
    </a>
  </h1>
  <?php if(Mage::getSingleton('customer/session')->isLoggedIn()) : ?>
    <div class="divider white"></div>
    <h1>
      <a href="<?php echo $this->getUrl('customer/account/logout'); ?>">
        <?php echo $this->__('Log Out')?>
      </a>
    </h1>
  <?php endif; ?>
</div>
<script type="text/javascript">
//<![CDATA[
jQuery(document).ready(function($) {
  $('a.level0').click(function(e) {

    if( !$(this).hasClass('has-children') ) {
      return;
    }
    e.preventDefault();

    var $parent = $(this).parent('.level0.parent');
    if( $parent.hasClass('expanded') ) {
      $parent.removeClass('expanded');
      $parent.find('ul.level0').removeClass('show');
    } else {
      $parent.addClass('expanded');
      $parent.find('ul.level0').addClass('show');
    }
  });

});
//]]>
</script>
