<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('deinverein-references')->toHtml(); ?>

<script type="text/javascript">
//<![CDATA[

  // jQuery('#deinverein-references').slick({
  //   dots: false,
  //   infinite: true,
  //   slidesToShow: 6,
  //   slidesToScroll: 1,
  //   responsive: [
  //     {
  //       breakpoint: 1024,
  //       settings: {
  //         slidesToShow: 5
  //       }
  //     },
  //     {
  //       breakpoint: 768,
  //       settings: {
  //         slidesToShow: 3
  //       }
  //     }
  //   ]
  // })

//]]>
</script>
