<?php
    $methods = $this->getMethods();
    $oneMethod = count($methods) <= 1;
?>
<?php if (empty($methods)): ?>
    <dt>
        <?php echo $this->__('No Payment Methods') ?>
    </dt>
<?php else:
    foreach ($methods as $_method):
        $_code = $_method->getCode();
?>
    <div id="dt_method_<?php echo $_code ?>" class="checkout-payment-method-wrapper">
      <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->escapeHtml($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
      <label for="p_method_<?php echo $_code ?>" class="method-title"><?php echo $this->escapeHtml($this->getMethodTitle($_method)) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
      <?php if($_code == 'ops_cc'): ?>
        <span class="icon-paymentmethod"><img src="<?php echo $this->getSkinUrl('images/icons/payment/icon-'.$_code.'.png') ?>" alt="<?php echo $_code ?>" style="max-width: 145px;" /></span>
      <?php else: ?>
        <span class="icon-paymentmethod"><img src="<?php echo $this->getSkinUrl('images/icons/payment/icon-'.$_code.'.svg') ?>" alt="<?php echo $_code ?>" /></span>
      <?php endif; ?>
      <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
        <div id="dd_method_<?php echo $_code ?>" class="payment-method-input-wrapper">
          <?php echo $html; ?>
        </div>
      <?php endif; ?>
    </div>
<?php endforeach;
    endif;
?>
<?php echo $this->getChildChildHtml('additional'); ?>
<script type="text/javascript">
    //<![CDATA[
    <?php echo $this->getChildChildHtml('scripts'); ?>
    payment.init();
    <?php if (is_string($oneMethod)): ?>
    payment.switchMethod('<?php echo $oneMethod ?>');
        <?php endif; ?>
    //]]>
</script>
