
<?php // totals für pdf prints ?>
<?php $_totals = $this->getTotals(); ?>

<?php foreach ($this->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
      <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
    <?php else: ?>
    <tr class="<?php echo $_code?>">
        <td style="text-align: right;" colspan="3">
          <?php if ($_total->getStrong()): ?>
            <strong><?php echo $this->escapeHtml($_total->getLabel());?></strong>
          <?php else: ?>
            <?php echo $this->escapeHtml($_total->getLabel());?>
          <?php endif; ?>
        </td>
        <td style="text-align: right;" colspan="2">
          <?php if ($_total->getStrong()): ?>
            <strong><?php echo $this->formatValue($_total) ?></strong>
          <?php else: ?>
            <?php echo $this->formatValue($_total) ?>
          <?php endif; ?>
        </td>
    </tr>
  <?php endif; ?>
<?php endforeach; ?>
