<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_category = mage::registry('current_category');
    $_showProductPrice = !($_category->getId() == 114);

    $_isShowHeadline = $this->getIsShowHeadline();
    $_toolbar = $this->getToolbarBlock();
?>
<div class="category-products">
<?php if($_isShowHeadline): ?>
  <h2><?php echo $_category->getName(); ?> <span class="products-count">/ <?php echo $_toolbar->getTotalNum() ?></span></h2>
<?php endif; ?>

<?php echo $this->getChildHtml('catalog.filter') ?>

<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php //echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
      <?php // no no list mode... - list mode not here ?>
    <?php else: ?>
    <?php // Grid Mode ?>

    <?php $gridSize = 4; ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
      <?php $i++ ?>
      <?php $manufacturer = $_product->getAttributeText('manufacturer'); ?>

      <?php $firstInRow = ($i % $gridSize == 1) ?>
      <?php $lastInRow = ($i % $gridSize == 0) ?>
      <?php $lastInCollection = ($i == $_collectionSize) ?>

      <?php // new row? ?>
      <?php if($firstInRow): ?>
        <div class="row full-width smaller-margins products-row">
      <?php endif ?>
          <div class="columns medium-3 small-6<?php echo ($lastInCollection ? ' end' : ''); ?>">
            <div class="productlist-element item">
              <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php $_imgSize = 210; ?>
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                   src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(232,245); ?>" width="232" height="245"
                   alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
              </a>
              <div class="product-info">
                <div class="top-row">
                  <h3><?php echo ($manufacturer != '' ? $manufacturer : '&nbsp;'); ?></h3>
                </div>
                <div class="bottom-row">
                  <div class="product-name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></div>
                  <?php if($_showProductPrice): ?><div class="price"><?php echo Mage::helper('core')->currency($_product->getFinalPrice(),true,false); ?></div><?php endif; ?>
                </div>
              </div>
              <?php
              if (false && $this->getChild('name.after')) {
                  $_nameAfterChildName = 'product_list.swatches';
                  if ($_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName)) {
                    echo '<div class="offcanvas offcanvas-left">';
                    $_nameAfterChild->setProduct($_product);
                    echo $_nameAfterChild->toHtml();
                    echo '</div>';
                  }
              }
              ?>
            </div>
          </div>

        <?php // close row? ?>
        <?php if ($lastInRow || $lastInCollection): ?>
          </div>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
      <?php echo $this->getToolbarHtml() ?>
    </div>
<?php endif; ?>
</div>
