<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>

<!DOCTYPE html>

<!--[if lt IE 7 ]> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js"> <!--<![endif]-->

<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<div id="site-wrapper">
  <div id="site-canvas">
    <?php echo $this->getChildHtml('after_body_start') ?>

    <!-- Include Header  -->
    <?php echo $this->getChildHtml('header') ?>

    <div class="wrapper">
        <?php echo $this->getChildHtml('global_notices') ?>
            <div id="main">
              <!-- HIER -->
              <div class="container">
                <?php echo $this->getChildHtml('breadcrumbs') ?>
                <div class="col-main">
                    <?php echo $this->getChildHtml('global_messages') ?>
                    <?php echo $this->getChildHtml('content') ?>
                    <?php echo $this->getChildHtml('promise') ?>
                </div>
            </div>
            <?php echo $this->getChildHtml('footer_before') ?>
            <?php echo $this->getChildHtml('footer') ?>
            <?php echo $this->getChildHtml('global_cookie_notice') ?>
            <?php echo $this->getChildHtml('before_body_end') ?>
        </div>
    </div>
    <?php echo $this->getChildHtml('jsfooter') ?>
    <?php echo $this->getAbsoluteFooter() ?>
    <div id='modal-global' class="hide"></div>

    <aside id="offcanvas-left-wrapper">
      <a class="offcanvas-close right toggle-nav"><i class="fa fa-times"></i></a>
      <div class="menu-wrapper">
        <?php echo $this->getChildHtml('top.menu.sidebar') ?>
      </div>
    </aside>
  </div>
</div>
</body>
</html>
